const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const statuses = {draft:'In progress',submitted:'In review',changes_requested:'Changes requested',approved:'Completed'};
const safeUrl = value => { try { const url = new URL(value); return ['https:','http:'].includes(url.protocol) && !url.username && !url.password ? url.href : ''; } catch { return ''; } };
const link = (url, label) => safeUrl(url) ? `<a href="${esc(safeUrl(url))}" target="_blank" rel="noopener noreferrer">${esc(label)} <span aria-hidden="true">↗</span></a>` : '';

export function roadmapHTML(roadmap, selectedId = '', drafts = {}) {
  if (!roadmap?.challenges?.length) return '<section class="section" id="beta-section-roadmap"><h2>Your learning roadmap</h2><div class="roadmap-wait"><p>Your challenges are being prepared. Arya and Milo will open the roadmap here when setup is complete.</p></div></section>';
  const {challenges} = roadmap;
  const completed = Math.max(0, Math.min(Number(roadmap.completed) || 0, challenges.length));
  const selected = challenges.find(item => item.id === selectedId && !item.locked) || challenges.find(item => item.id === roadmap.currentChallengeId && !item.locked) || challenges.find(item => !item.locked && item.submission?.status !== 'approved') || challenges.filter(item => !item.locked).at(-1);
  const nodes = challenges.map((challenge, index) => {
    const status = challenge.locked ? 'locked' : challenge.submission?.status || 'ready';
    return `<li class="roadmap-step ${esc(status)}${selected?.id === challenge.id ? ' selected' : ''}"><button type="button" data-roadmap-select="${esc(challenge.id)}"${challenge.locked ? ' disabled data-roadmap-locked="true"' : ''} aria-pressed="${selected?.id === challenge.id}"><span class="roadmap-node" aria-hidden="true">${status === 'approved' ? '✓' : String(index + 1).padStart(2,'0')}</span><span class="roadmap-step-copy"><span class="roadmap-step-status">${challenge.locked ? 'Locked · complete the previous challenge' : statuses[status] || 'Ready to start'}</span><strong>${esc(challenge.title)}</strong><span>${esc(challenge.teaser || '')}</span></span><span class="roadmap-step-arrow" aria-hidden="true">${challenge.locked ? '⌑' : '↗'}</span></button></li>`;
  }).join('');
  const rewards = `<div class="roadmap-rewards"><span class="${roadmap.unlocks?.peerWork ? 'unlocked' : ''}">${roadmap.unlocks?.peerWork ? '✓' : '01'} <strong>Peer gallery</strong><small>${roadmap.unlocks?.peerWork ? 'Unlocked' : 'After challenge 1'}</small></span><span class="${roadmap.unlocks?.teamReferences ? 'unlocked' : ''}">${roadmap.unlocks?.teamReferences ? '✓' : '02'} <strong>Team examples</strong><small>${roadmap.unlocks?.teamReferences ? 'Unlocked' : 'After challenge 2'}</small></span><span class="${completed === challenges.length ? 'unlocked' : ''}">↗ <strong>Keep building</strong><small>A new challenge with each approval</small></span></div>`;
  return `<section class="section roadmap" id="beta-section-roadmap" aria-labelledby="beta-heading-roadmap"><div class="roadmap-hero"><div><span class="eyebrow">LEARN BY SHIPPING</span><h2 id="beta-heading-roadmap">Small steps. Real skills.</h2><p>Build, publish, get feedback. Every completed challenge opens the next step.</p></div><div class="roadmap-progress"><strong>${completed}<span> / ${challenges.length}</span></strong><span>challenges completed</span><progress max="${challenges.length}" value="${completed}" aria-label="Challenges completed">${completed} of ${challenges.length}</progress></div></div>${rewards}<div class="roadmap-layout"><ol class="roadmap-path" aria-label="Challenge roadmap">${nodes}</ol><div id="beta-challenge-detail" class="roadmap-detail">${selected ? challengeHTML(selected, drafts[selected.id], challenges.indexOf(selected) + 1) : ''}</div></div></section>`;
}

function challengeHTML(challenge, draft, number) {
  const saved = challenge.submission || {}, source = draft || saved;
  const readOnly = ['submitted','approved'].includes(saved.status);
  const revision = challenge.revision || '';
  const changed = !readOnly && Boolean(draft || saved.status) && (source.challengeRevision || '') !== revision;
  const values = changed ? {...source, checks: []} : source;
  const minIterations = Number.isInteger(challenge.minIterations) ? challenge.minIterations : challenge.id === 'spend-portal' ? 3 : 0;
  const checks = Array.isArray(values.checks) ? values.checks : [];
  const checklist = (challenge.checklist || []).map(item => `<label class="challenge-check"><input type="checkbox" name="checks" value="${esc(item.id)}"${checks.includes(item.id) ? ' checked' : ''}${readOnly ? ' disabled data-roadmap-locked="true"' : ''}><span>${esc(item.label)}</span></label>`).join('');
  const feedback = saved.feedback ? `<div class="challenge-feedback"><strong>${saved.status === 'changes_requested' ? 'Your next improvements' : 'Reviewer feedback'}</strong><p>${esc(saved.feedback)}</p></div>` : '';
  const state = saved.status === 'approved' ? '<p class="challenge-state success">✓ Approved. This challenge is complete.</p>' : saved.status === 'submitted' ? '<p class="challenge-state">Your work is with Arya and Milo. Approval unlocks your next step.</p>' : '<p class="challenge-help">Save your progress anytime. When everything is ready, submit for Arya or Milo to review.</p>';
  const evidence = readOnly ? `<div class="challenge-evidence">${link(saved.liveUrl,'Visit live project')}${link(saved.repoUrl,'View repository')}<p>${esc(saved.notes)}</p>${(saved.iterationLinks || []).map((url,index) => link(url,'Iteration ' + (index + 1))).join('')}</div>` : `<div class="challenge-fields"><label>Live project URL<input name="liveUrl" type="text" inputmode="url" autocapitalize="none" spellcheck="false" maxlength="300" placeholder="https://yourname.com" value="${esc(values.liveUrl)}"></label><label>Public GitHub repository<input name="repoUrl" type="url" maxlength="300" placeholder="https://github.com/you/project" value="${esc(values.repoUrl)}"></label><label>What did you build and learn?<textarea name="notes" rows="4" maxlength="5000" placeholder="Explain what works, what you changed, and how you checked it.">${esc(values.notes)}</textarea></label>${minIterations > 0 || (values.iterationLinks || []).length ? `<label>Published iterations <span>One GitHub commit or compare link per line${minIterations > 0 ? ' · at least ' + minIterations + ' distinct follow-up ' + (minIterations === 1 ? 'push' : 'pushes') : ''}</span><textarea name="iterationLinks" rows="3" maxlength="12000" placeholder="https://github.com/you/project/commit/…">${esc((values.iterationLinks || []).join('\n'))}</textarea></label>` : ''}</div>`;
  return `<div class="challenge-heading"><span class="eyebrow">CHALLENGE ${String(number).padStart(2,'0')}</span><span class="challenge-badge ${esc(saved.status || 'ready')}">${statuses[saved.status] || 'Your next step'}</span></div><h3 tabindex="-1" id="beta-selected-challenge">${esc(challenge.title)}</h3><p class="challenge-brief">${esc(challenge.brief)}</p>${feedback}<form data-challenge-form="${esc(challenge.id)}" data-challenge-revision="${esc(revision)}" novalidate><fieldset class="challenge-checklist"><legend>What you’ll ship</legend>${checklist}</fieldset>${evidence}${state}${!readOnly ? '<div class="challenge-actions"><button class="button" type="submit" value="draft">Save draft</button><button class="button primary" type="submit" value="submit">Submit for review <span aria-hidden="true">↗</span></button></div>' : ''}<p class="challenge-draft-state" aria-live="polite">${changed ? 'The requirements changed. Review the checklist before submitting; your links and notes are kept.' : draft ? 'Unsaved changes' : saved.updatedAt && !readOnly ? 'Draft saved' : ''}</p></form>`;
}

export function challengeFormValues(form) {
  const value = name => String(form.elements.namedItem(name)?.value || '').trim();
  return {challengeId:form.dataset.challengeForm,challengeRevision:form.dataset.challengeRevision || '',liveUrl:value('liveUrl'),repoUrl:value('repoUrl'),notes:value('notes'),checks:Array.from(form.querySelectorAll('input[name="checks"]:checked'),element=>element.value),iterationLinks:value('iterationLinks').split('\n').map(item=>item.trim()).filter(Boolean)};
}

export function roadmapLibraryHTML(roadmap) {
  const peerOpen = roadmap?.unlocks?.peerWork === true, teamOpen = roadmap?.unlocks?.teamReferences === true;
  const peers = peerOpen ? (roadmap.peerWork || []).map(item=>`<article class="roadmap-project"><span class="eyebrow">${esc(item.name)}</span><h3>${esc(item.title)}</h3><div>${link(item.liveUrl,'Live project')}${link(item.repoUrl,'Code')}</div></article>`).join('') : '';
  const references = teamOpen ? (roadmap.references || []).map(item=>`<article class="roadmap-project"><span class="eyebrow">TEAM EXAMPLE</span><h3>${esc(item.title)}</h3><p>${esc(item.notes)}</p><div>${link(item.url,'Explore example')}</div></article>`).join('') : '';
  return `<section class="section" id="beta-section-library" aria-labelledby="beta-heading-library"><div class="section-head"><div><h2 id="beta-heading-library">Your inspiration library</h2><p class="section-description">Build your own first. Then learn from how others approached it.</p></div></div><div class="roadmap-library"><div class="roadmap-library-group"><div class="roadmap-library-title"><h3>What other interns built</h3><span>${peerOpen ? 'Unlocked' : 'Locked'}</span></div>${peerOpen ? peers || '<p class="roadmap-library-empty">The gallery is open. Approved projects from your group will appear here as they finish.</p>' : '<p class="roadmap-library-empty">Complete your first challenge to explore your group’s approved projects and GitHub work.</p>'}</div><div class="roadmap-library-group"><div class="roadmap-library-title"><h3>How we built it</h3><span>${teamOpen ? 'Unlocked' : 'Locked'}</span></div>${teamOpen ? references || '<p class="roadmap-library-empty">You’ve unlocked team examples. Arya and Milo can add the team’s portfolio and spend portal demos here.</p>' : '<p class="roadmap-library-empty">Complete your second challenge to unlock our examples and the next challenges.</p>'}</div></div></section>`;
}
