const MAX_FILE=10*1024*1024;
const extensions=new Set(['pdf','csv','xlsx','xls','ics','doc','docx','png','jpg','jpeg','webp','mp4','mov']);
export function validEvent(event){return typeof event?.title==='string'&&event.title.trim().length>0&&/^\d{4}-\d{2}-\d{2}$/.test(event.date||'')&&Number.isFinite(Date.parse(event.date+'T12:00:00Z'))&&new Date(event.date+'T12:00:00Z').toISOString().slice(0,10)===event.date;}
export function calendarReady(calendar){return Boolean(calendar?.file)||(Array.isArray(calendar?.events)&&calendar.events.length>0&&calendar.events.every(validEvent));}
export function fileError(file){if(!extensions.has(file.name.split('.').pop().toLowerCase()))return'Choose a PDF, spreadsheet, calendar, document, or image file.';if(!file.size)return'This file is empty. Choose another file.';if(file.size>MAX_FILE)return'Please choose a file smaller than 10 MB.';return'';}
function database(){return new Promise((resolve,reject)=>{const request=indexedDB.open('fomo-task-calendar-files',1);request.onupgradeneeded=()=>request.result.createObjectStore('files');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function fileStore(id,action,file){const db=await database();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('files',action==='get'?'readonly':'readwrite'),store=tx.objectStore('files');let result;const request=action==='put'?store.put(file,id):action==='delete'?store.delete(id):store.get(id);request.onsuccess=()=>{result=request.result;};tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}finally{db.close();}}
export const getCalendarFile=id=>fileStore(id,'get');
export const storeTaskFile=(id,file)=>fileStore(id,'put',file);
export function createCalendar({getProfile,save,onProgress,downloadShared}){
 const card=document.querySelector('[data-task="calendar"]'),eventsNode=document.querySelector('#calendar-events'),status=document.querySelector('#calendar-status'),fileInput=document.querySelector('#calendar-file'),drop=document.querySelector('#calendar-drop');
 let busy=false;
 function value(){const p=getProfile();if(!p)return null;p.calendar??={events:[],file:null};if(!Array.isArray(p.calendar.events))p.calendar.events=[];return p.calendar;}
 function update(){const calendar=value();card.querySelector('[data-check]').checked=calendarReady(calendar);onProgress(card);}
 function attachment(){const file=value()?.file;document.querySelector('#calendar-attachment').hidden=!file;document.querySelector('#calendar-file-name').textContent=file?`${file.name} · ${(file.size/1024/1024).toFixed(1)} MB`:'';}
 function drawEvents(){eventsNode.replaceChildren();const calendar=value();if(!calendar)return;calendar.events.forEach((event,index)=>{const row=document.createElement('div');row.className='calendar-event';for(const [field,label,type] of [['title','Event name','text'],['date','Event date','date'],['time','Time (optional)','time']]){const wrap=document.createElement('label');wrap.textContent=label;const input=document.createElement('input');input.type=type;input.value=event[field]||'';input.maxLength=160;input.setAttribute('aria-label',`${label} ${index+1}`);input.addEventListener('input',()=>{event[field]=input.value;update();save();});wrap.append(input);row.append(wrap);}const remove=document.createElement('button');remove.type='button';remove.className='quiet-button';remove.textContent='Remove';remove.setAttribute('aria-label',`Remove event ${index+1}`);remove.addEventListener('click',()=>{calendar.events.splice(index,1);drawEvents();update();save();});row.append(remove);eventsNode.append(row);});}
 async function render(){const profile=getProfile();if(!profile)return;status.textContent='';fileInput.value='';drawEvents();attachment();update();if(profile.calendar?.file&&!profile.calendar.file.id){try{const file=await fileStore(profile.id,'get');if(!file){profile.calendar.file=null;if(getProfile()?.id===profile.id){attachment();update();save();status.textContent='The saved file is unavailable. Please attach it again.';}}}catch{if(getProfile()?.id===profile.id)status.textContent='Couldn’t open browser file storage. Your dates are still available.';}}}
 async function accept(file){if(!file||busy)return;if(getProfile()?.cloud?.tasks.some(t=>t.taskId==='calendar'&&t.status==='approved')){status.textContent='This calendar is approved. Ask fomo to request changes before replacing it.';return;}const profile=getProfile();if(!profile)return;const invalid=fileError(file);if(invalid){status.textContent=invalid;return;}busy=true;fileInput.disabled=true;status.textContent='Saving file…';try{await fileStore(profile.id,'put',file);profile.calendar??={events:[]};profile.calendar.file={name:file.name,size:file.size,type:file.type};if(getProfile()?.id===profile.id){attachment();update();save();status.textContent='File ready. Saving it to fomo…';}}catch{status.textContent='Couldn’t save this file. Try again, or enter your event dates instead.';}finally{busy=false;fileInput.disabled=false;fileInput.value='';}}
 fileInput.addEventListener('change',()=>void accept(fileInput.files?.[0]));for(const type of ['dragenter','dragover'])drop.addEventListener(type,e=>{e.preventDefault();drop.classList.add('drag-over');});for(const type of ['dragleave','drop'])drop.addEventListener(type,e=>{e.preventDefault();drop.classList.remove('drag-over');});drop.addEventListener('drop',e=>{if(e.dataTransfer.files.length>1){status.textContent='Please attach one calendar file at a time.';return;}void accept(e.dataTransfer.files[0]);});
 document.querySelector('#add-event').addEventListener('click',()=>{const calendar=value();if(!calendar)return;if(calendar.events.length>=100){status.textContent='You can add up to 100 events, or attach a calendar file.';return;}calendar.events.push({title:'',date:'',time:''});drawEvents();update();save();eventsNode.querySelector('.calendar-event:last-child input')?.focus();});
 document.querySelector('#remove-calendar').addEventListener('click',async()=>{const profile=getProfile();if(!profile||busy)return;try{await fileStore(profile.id,'delete');profile.calendar.file=null;attachment();update();save();status.textContent='File removed from this profile.';}catch{status.textContent='Couldn’t remove the file. Please try again.';}});
 document.querySelector('#download-calendar').addEventListener('click',async()=>{try{if(getProfile().calendar?.file?.id){await downloadShared(getProfile().calendar.file.id);return;}const file=await fileStore(getProfile().id,'get');if(!file)throw Error();const url=URL.createObjectURL(file),link=document.createElement('a');link.href=url;link.download=file.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{status.textContent='Couldn’t download the saved file. Please attach it again.';}});
 return{render,text:()=>{const calendar=value();if(!calendar)return'';const lines=calendar.events.filter(validEvent).map(e=>`${e.date}${e.time?' at '+e.time:''} — ${e.title.trim()}`);if(calendar.file)lines.unshift(`Calendar file: ${calendar.file.name} (send this file with the update)`);return lines.join('\n');}};
}
