import {savedChecks} from './profile.js';
import {getCalendarFile} from './calendar.js';
export const TASK_ENDPOINT='https://script.google.com/macros/s/AKfycbyeQIRm2DezB1fYi0B03pnbuorco5eQAAJtxioVClgB4xyMVWGlvVmAFQqFdwbI3UnZfA/exec';
export async function taskRequest(token,action,payload={}){const response=await fetch(TASK_ENDPOINT,{method:'POST',body:JSON.stringify({_api:'campusTasks',_taskToken:token,action,...payload}),signal:AbortSignal.timeout(60000)});if(!response.ok)throw Error('The shared service is unavailable. Your draft is still saved here.');const out=await response.json();if(!out.ok&&out.code==='AUTH_REQUIRED'&&typeof window!=='undefined')window.dispatchEvent(new CustomEvent('campus-auth-required',{detail:{token}}));if(!out.ok)throw Object.assign(Error(/unknown form/.test(out.error||'')?'Shared task tracking is being enabled. Your draft is saved here; try again shortly.':out.error||'Could not save your update.'),{code:out.code});return out;}
export async function filePayload(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(Error('Could not read the calendar file.'));reader.onload=()=>resolve({name:file.name,type:file.type,data:String(reader.result).split(',')[1]});reader.readAsDataURL(file);});}
export function downloadTaskFile(file){const bytes=Uint8Array.from(atob(file.data),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:file.type})),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function createSharedTasks({getProfile,write,onState,onRestore,onMessage}){
 const chains=new Map(),timers=new Map();
 function queued(profile,fn){const next=(chains.get(profile.id)||Promise.resolve()).catch(()=>{}).then(fn);chains.set(profile.id,next);return next;}
 function install(profile,out){profile.cloud={member:out.member,tasks:out.tasks,steps:out.steps||[]};write();if(getProfile()?.id===profile.id)onState();}
 async function connect(profile){if(!profile.token||!profile.account)throw Error('Sign in to save your work.');const out=await taskRequest(profile.token,'get');if(profile.cloud){for(const step of out.steps||[]){const key=step.taskId+':'+step.step,known=profile.cloud.steps?.find(s=>s.taskId===step.taskId&&Number(s.step)===Number(step.step));if(profile.stepDrafts?.[key]?._dirty&&Number(known?.revision||0)!==Number(step.revision))throw Error('This step changed on another device. Use “Load saved progress” before continuing. Your local draft is still here.');}}if(profile.cloud&&profile.dirty){for(const task of out.tasks){const known=profile.cloud.tasks.find(t=>t.taskId===task.taskId);if(known&&Number(known.revision)!==Number(task.revision))throw Error('Your shared progress changed on another device. Use “Load saved progress” before continuing. Your local draft is still here.');}}install(profile,out);return out;}
 function draft(profile,id){const data=profile.progress?.[id]||{checks:[],chapter:profile.school.name,notes:''};return {...data,checks:savedChecks(id,data.checks),...(id==='calendar'?{calendar:{events:profile.calendar?.events||[],file:profile.calendar?.file?.id?profile.calendar.file:null}}:{})};}
 async function send(profile,submitId){const editVersion=profile.editVersion||0;if(!profile.cloud)await connect(profile);if(profile.calendar?.file&&!profile.calendar.file.id){const file=await getCalendarFile(profile.id);if(!file)throw Error('Please reattach your calendar file.');const metadata=profile.calendar.file;const out=await taskRequest(profile.token,'upload',{file:await filePayload(file)});if(profile.calendar.file===metadata){profile.calendar.file=out.file;write();}}
 for(const id of ['dinner','filmer','host','travel','calendar','referral']){if(!profile.progress?.[id]&&id==='referral')continue;const current=profile.cloud.tasks.find(t=>t.taskId===id),data=draft(profile,id);if(!current&&id!==submitId&&!data.checks.some(Boolean)&&!data.notes&&!(data.calendar?.events.length||data.calendar?.file))continue;if(current?.status==='approved'){if(id===submitId)throw Error('This task is already approved.');continue;}if(id!==submitId&&current&&JSON.stringify(data)===JSON.stringify(current.draft))continue;const out=await taskRequest(profile.token,id===submitId?'submit':'save',{taskId:id,revision:current?.revision||0,draft:data});install(profile,out);}profile.dirty=(profile.editVersion||0)!==editVersion;write();if(getProfile()?.id===profile.id){onState();onMessage(profile.dirty?'Saving your latest changes…':'Saved to fomo.');}}
 function run(profile,submitId){return queued(profile,async()=>{try{if(getProfile()?.id===profile.id)onMessage(submitId?'Submitting to fomo…':'Saving to fomo…');await send(profile,submitId);if(submitId&&getProfile()?.id===profile.id)onMessage('Submitted. fomo will review your update.');}catch(error){if(getProfile()?.id===profile.id)onMessage(error.message,true);throw error;}});}
 function schedule(){const p=getProfile();if(!p)return;p.dirty=true;p.editVersion=(p.editVersion||0)+1;write();clearTimeout(timers.get(p.id));timers.set(p.id,setTimeout(()=>{run(p).catch(()=>{});},1200));}
 async function start(profile){return queued(profile,async()=>{try{onMessage('Connecting to your saved progress…');const hadCloud=!!profile.cloud;await connect(profile);if(hadCloud&&!profile.dirty){restore(profile);onMessage('Your progress is saved with fomo.');}else await send(profile);}catch(error){if(getProfile()?.id===profile.id)onMessage(error.message,true);}});}
 function restore(profile,force=false){profile.stepDrafts??={};for(const step of profile.cloud.steps||[]){const key=step.taskId+':'+step.step;if(force||!profile.stepDrafts[key]?._dirty)profile.stepDrafts[key]=step.draft;}for(const task of profile.cloud.tasks){profile.progress[task.taskId]=task.draft;if(task.taskId==='calendar')profile.calendar=task.draft.calendar||{events:[],file:null};}profile.dirty=false;write();if(getProfile()?.id===profile.id)onRestore();}
 async function reload(){const p=getProfile();clearTimeout(timers.get(p.id));return queued(p,async()=>{const out=await taskRequest(p.token,'get');install(p,out);restore(p,true);onMessage('Loaded your progress from fomo.');});}
 return{schedule,start,reload,step(profile,taskId,index,submit=false){return queued(profile,async()=>{if(!profile.cloud)await connect(profile);if(taskId==='calendar')await send(profile);const key=taskId+':'+index,d=profile.stepDrafts?.[key]||{notes:'',files:[]};for(const file of d.files||[]){if(file.id)continue;const blob=await getCalendarFile(file.localId);if(!blob)throw Error('Please reattach '+file.name);const uploaded=await taskRequest(profile.token,'upload',{file:await filePayload(blob)});Object.assign(file,uploaded.file);delete file.localId;write();}const version=d._version||0;const row=profile.cloud.steps?.find(s=>s.taskId===taskId&&Number(s.step)===index);const out=await taskRequest(profile.token,submit?'submitstep':'savestep',{taskId,step:index,revision:row?.revision||0,draft:{notes:d.notes||'',files:d.files||[],...(taskId==='calendar'?{calendar:profile.calendar||{events:[],file:null}}:{})}});if((d._version||0)===version)d._dirty=false;install(profile,out);return out;});},submit(id){const p=getProfile();clearTimeout(timers.get(p.id));return run(p,id);},async download(fileId){downloadTaskFile((await taskRequest(getProfile().token,'file',{fileId})).file);}};
}
