import {storeTaskFile,fileError} from './calendar.js';
export function createStepEditors({getProfile,write,shared,onChange}) {
  const editors=[...document.querySelectorAll('[data-step-editor]')],timers=new Map(),busy=new Set();
  const keyOf=el=>el.dataset.taskId+':'+el.dataset.step;
  const draft=(p,key)=>(p.stepDrafts??={})[key]??=(p.cloud?.steps||[]).find(s=>s.taskId+':'+s.step===key)?.draft||{notes:'',files:[]};
  const row=(p,el)=>p.cloud?.steps?.find(s=>s.taskId===el.dataset.taskId&&Number(s.step)===Number(el.dataset.step));
  function locked(p,el){return p.cloud?.tasks?.some(t=>t.taskId===el.dataset.taskId&&t.status==='approved')||row(p,el)?.status==='approved';}
  function message(el,text){el.querySelector('[data-step-message]').textContent=text;}
  function files(el,p){const container=el.querySelector('[data-step-files]');container.replaceChildren();for(const file of draft(p,keyOf(el)).files||[]){const item=document.createElement('div'),name=document.createElement('span');item.className='step-file';name.textContent=file.name;item.append(name);if(file.id){const download=document.createElement('button');download.type='button';download.className='quiet-button';download.textContent='Download';download.addEventListener('click',async()=>{try{await shared.download(file.id);}catch(e){message(el,e.message);}});item.append(download);}if(!locked(p,el)){const remove=document.createElement('button');remove.type='button';remove.className='quiet-button';remove.textContent='Remove';remove.addEventListener('click',()=>{const d=draft(p,keyOf(el));d.files=d.files.filter(f=>f!==file);write();files(el,p);schedule(el,p);});item.append(remove);}container.append(item);}}
  function paint(){const p=getProfile();if(!p)return;for(const el of editors){const r=row(p,el),isLocked=locked(p,el),sending=busy.has(p.id+':'+keyOf(el));el.querySelector('[data-step-notes]').disabled=isLocked;el.querySelector('[data-step-upload]').disabled=isLocked||sending;const button=el.querySelector('[data-step-submit]');button.disabled=isLocked||sending;button.textContent=isLocked?'Approved':r?.status==='submitted'?'Resubmit step':'Send step for review';el.querySelector('[data-step-status]').textContent=isLocked?'Approved':({draft:'Draft',submitted:'In review',changes_requested:'Changes requested'})[r?.status]||'Not submitted';const feedback=el.querySelector('[data-step-feedback]');feedback.hidden=!r?.feedback;feedback.textContent=r?.feedback?'fomo: '+r.feedback:'';files(el,p);}}
  function restore(){const p=getProfile();if(!p)return;for(const el of editors){el.querySelector('[data-step-notes]').value=draft(p,keyOf(el)).notes||'';message(el,'');if(draft(p,keyOf(el))._dirty)schedule(el,p);}paint();}
  async function send(el,p,submit){const id=p.id+':'+keyOf(el);clearTimeout(timers.get(id));busy.add(id);paint();message(el,submit?'Sending this step…':'Saving step…');try{await shared.step(p,el.dataset.taskId,Number(el.dataset.step),submit);if(getProfile()?.id===p.id){message(el,submit?'Sent to fomo. You can keep working on the other steps.':'Step saved.');onChange();}}catch(e){if(getProfile()?.id===p.id)message(el,e.message);}finally{busy.delete(id);if(getProfile()?.id===p.id)paint();}}
  function schedule(el,p){const d=draft(p,keyOf(el));d._dirty=true;d._version=(d._version||0)+1;write();const id=p.id+':'+keyOf(el);clearTimeout(timers.get(id));timers.set(id,setTimeout(()=>void send(el,p,false),1200));}
  for(const el of editors){el.querySelector('[data-step-notes]').addEventListener('input',event=>{const p=getProfile();if(!p)return;draft(p,keyOf(el)).notes=event.target.value;write();schedule(el,p);});el.querySelector('[data-step-submit]').addEventListener('click',()=>{const p=getProfile();if(p)void send(el,p,true);});el.querySelector('[data-step-upload]').addEventListener('change',async event=>{const p=getProfile();if(!p||locked(p,el))return;const input=event.target,picked=[...input.files],d=draft(p,keyOf(el));if((d.files||[]).length+picked.length>5){message(el,'Attach up to five files per step.');input.value='';return;}const error=picked.map(fileError).find(Boolean);if(error){message(el,error);input.value='';return;}try{for(const file of picked){const localId=p.id+':step:'+crypto.randomUUID();await storeTaskFile(localId,file);(d.files??=[]).push({localId,name:file.name,size:file.size,type:file.type});}d._dirty=true;d._version=(d._version||0)+1;write();if(getProfile()?.id===p.id){files(el,p);message(el,'Uploading attachments…');}void send(el,p,false);}catch{message(el,'Could not save the attachment. Please try again.');}finally{input.value='';}});}
  return {paint,restore};
}
