import {startFeed,summarize} from './model.mjs';
import {createScene} from './scene.js';
import {createTerminal} from './terminal.js';
import {createChimePlayer} from './sound.js';
const $=id=>document.getElementById(id),fmt=n=>n.toLocaleString('en-US'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let chapters=[],selected=null,scene,paused=reduced,latest=null,isLive=false,toastTimer,eventQueue=[],eventBusy=false,shownEvents=[];
try{scene=createScene({container:$('scene'),labels:$('labels'),tooltip:$('tooltip'),onSelect:select,reduced});}catch{$('loading-text').textContent='3D unavailable — live chapter details remain below';$('loading').querySelector('.loader-ring').hidden=true;}
const terminal=createTerminal({select,getSelected:()=>selected,openDirectory,scene});
function select(id){const c=chapters.find(c=>c.id===id);if(!c)return;selected=id;scene?.select(id);$('chapter-symbol').textContent=c.letters;$('chapter-name').textContent=c.name;$('chapter-school').textContent=c.school;$('selected-joined').textContent=fmt(c.joined);$('selected-active').textContent=fmt(c.active);$('selected-target').textContent=fmt(Math.ceil(c.active*.8));$('selected-remaining').textContent=fmt(Math.max(0,Math.ceil(c.active*.8)-c.joined));$('selected-date').textContent=new Date(c.registered+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'2-digit',timeZone:'UTC'});$('selected-type').textContent=c.type;$('ring-value').style.strokeDashoffset=427.26*(1-Math.min(1,c.joined/c.active));terminal.selection();}
function render(s,events){
 const changed=JSON.stringify(chapters)!==JSON.stringify(s.chapters);chapters=s.chapters;latest=s.updatedAt;
 terminal.update(s);const totals=summarize(chapters);$('total').textContent=fmt(totals.joined);$('total-note').textContent='Across the collective';$('schools').textContent=fmt(totals.schools);$('chapters').textContent=fmt(totals.chapters);$('node-count').textContent=fmt(totals.chapters);$('participation').textContent=(totals.participation*100).toFixed(1)+'%';$('participation-bar').style.width=Math.min(100,totals.participation*100)+'%';$('roster-caption').textContent=fmt(totals.joined)+' joined / '+fmt(totals.active)+' active roster';
 if(scene){$('loading').hidden=true;if(changed){const info=scene.update(chapters);document.querySelector('.encoding p').lastChild.textContent=info.particleStep===1?' An eye particle = a member':' An eye particle ≈ '+info.particleStep+' members';}}
 if(changed){renderLeaders();renderGrowth();if($('directory').open)renderDirectory();}
 if(!chapters.some(c=>c.id===selected))selected=[...chapters].sort((a,b)=>b.joined-a.joined)[0]?.id;
 if(selected)select(selected);else{$('chapter-name').textContent='No chapters yet';$('chapter-school').textContent='Waiting for the first registration.';}
 if(events.length){eventQueue.push(...events);playNext();}
}
function renderLeaders(){terminal.renderWatch();}
function renderGrowth(){terminal.chart();}
function renderDirectory(){const query=$('search').value.trim().toLowerCase(),filtered=[...chapters].filter(c=>[c.name,c.school,c.type,c.letters,c.registered].some(v=>v.toLowerCase().includes(query))).sort((a,b)=>b.joined-a.joined);$('results-count').textContent=filtered.length+' CHAPTER RECORDS';$('directory-results').replaceChildren();if(!filtered.length){const p=document.createElement('p');p.className='muted';p.textContent='No matching chapters. Try another name or school.';$('directory-results').append(p);}filtered.forEach(c=>{const b=document.createElement('button');b.className='directory-row';const div=document.createElement('div'),name=document.createElement('strong'),school=document.createElement('small'),n=document.createElement('b');name.textContent=c.letters+' · '+c.name;school.textContent=c.school+' · '+c.registered;n.textContent=fmt(c.joined)+' / '+fmt(c.active);div.append(name,school);b.append(div,n);b.onclick=()=>{select(c.id);$('directory').close();$('stage').scrollIntoView({behavior:reduced?'instant':'smooth',block:'center'});};$('directory-results').append(b);});}
function openDirectory(){$('directory').showModal();$('search').value='';renderDirectory();$('search').focus();}
$('open-directory').onclick=openDirectory;$('close-directory').onclick=()=>$('directory').close();$('search').oninput=renderDirectory;$('directory').addEventListener('click',e=>{if(e.target===$('directory')){const r=$('directory').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('directory').close();}});
const descriptions={eyes:'01 — FOMO NEURAL CORE',organism:'02 — THE CHAPTER NETWORK',constellation:'03 — SCHOOL CONSTELLATIONS',helix:'04 — REGISTRATION TIMELINE'};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{scene?.setMode(b.dataset.mode);document.querySelectorAll('[data-mode]').forEach(el=>{el.classList.toggle('selected',el===b);el.setAttribute('aria-pressed',String(el===b));});$('view-caption').textContent=descriptions[b.dataset.mode];$('view-explanation').textContent={eyes:'The FOMO eyes, built from your live membership. Select a chapter to trace its signal.',organism:'Chapters orbit a shared core. Larger nuclei hold more registrations.',constellation:'Chapter records cluster by school. Colors stay with their school.',helix:'Chapter registration dates spiral upward: earliest below, newest above.'}[b.dataset.mode];});
function updateMotion(){document.body.classList.toggle('paused',paused);$('motion').textContent=paused?'Resume motion':'Pause motion';$('motion').setAttribute('aria-pressed',String(paused));scene?.setPaused(paused);}updateMotion();$('motion').onclick=()=>{paused=!paused;updateMotion();};$('reset').onclick=()=>scene?.reset();
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{$('fullscreen').title='Fullscreen unavailable in this browser';}};
const chimes=createChimePlayer();
function soundState(){const on=chimes.enabled;$('sound').textContent=on?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(on));$('sound').title=on?'Mute member and goal chimes':'Enable member and goal chimes';}
function stopAutoSound(){document.removeEventListener('pointerdown',autoSound);document.removeEventListener('keydown',autoSound);}
async function autoSound(event){if(event.target.closest?.('#sound'))return;if(await chimes.enable()){stopAutoSound();soundState();}}
document.addEventListener('pointerdown',autoSound);document.addEventListener('keydown',autoSound);
$('sound').textContent='Enable sound';$('sound').title='Sound activates on your first click or keypress';
$('sound').onclick=async()=>{stopAutoSound();if(chimes.enabled)chimes.disable();else if(await chimes.enable())chimes.play('arrival');soundState();};
function playNext(){if(eventBusy||!eventQueue.length)return;const event=eventQueue.shift();eventBusy=true;notify(event,false);setTimeout(()=>{eventBusy=false;playNext();},6400);}
function notify({chapter:c,count,goalReached=false},preview){
 scene?.pulse(c.id,count);terminal.arrival();$('toast-kicker').textContent=preview?'SOUND PREVIEW · COUNTS UNCHANGED':goalReached?'CHAPTER GOAL REACHED':'NEW ENERGY DETECTED';$('toast-title').textContent=preview?(goalReached?'Goal celebration preview':'New member chime preview'):goalReached?`${c.name} hit its goal!`:`${fmt(count)} new ${count===1?'member':'members'} joined.`;$('toast-subtitle').textContent=c.name+' · '+c.school;$('toast-count').textContent=preview?'✳':'+'+fmt(count);$('arrival-toast').classList.toggle('goal-reached',goalReached);$('arrival-toast').classList.remove('show');void $('arrival-toast').offsetWidth;$('arrival-toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('arrival-toast').classList.remove('show'),6100);chimes.play(goalReached?'goal':'arrival');
 if(!preview){shownEvents.unshift({name:c.name,school:c.shortSchool,count,goalReached,at:new Date().toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'})});shownEvents=shownEvents.slice(0,3);$('event-list').replaceChildren();shownEvents.forEach(e=>{const row=document.createElement('div');row.className='event';const count=document.createElement('b'),text=document.createElement('div'),name=document.createElement('strong'),meta=document.createElement('span');count.textContent='+'+e.count;name.textContent=e.name+(e.goalReached?' · Goal reached!':'');meta.textContent=e.school+' · observed '+e.at;text.append(name,meta);row.append(count,text);$('event-list').append(row);});}
}
async function previewSound(goalReached){const c=chapters.find(c=>c.id===selected)||chapters[0];if(!c||eventBusy)return;await chimes.enable();soundState();notify({chapter:c,count:1,goalReached},true);}
$('preview-arrival').onclick=()=>previewSound(false);
$('preview-goal').onclick=()=>previewSound(true);
function status(s){if(s.updatedAt)latest=s.updatedAt;isLive=s.live;updateFreshness();if(!chapters.length&&!s.live){$('loading-text').textContent='Signal unavailable — reconnecting automatically';$('total-note').textContent='Waiting for live data';}}
function updateFreshness(){const age=latest?Math.max(0,Math.floor((Date.now()-Date.parse(latest))/1000)):null,live=isLive&&age!==null&&age<=90;$('status').classList.toggle('live',live);$('status').querySelector('span').textContent=live?'LIVE FEED':latest?'SAVED SIGNAL':'CONNECTING';$('freshness').textContent=latest?`${live?'Synced':'Last received'} ${age<60?age+'s':Math.floor(age/60)+'m'} ago · checks every 30s${live?'':' · reconnecting'}`:'Connecting to live registrations';}
const feed=startFeed({onData:render,onStatus:status});$('refresh').onclick=()=>feed.refresh();const freshnessTimer=setInterval(updateFreshness,1000);window.addEventListener('pagehide',()=>{stopAutoSound();feed.stop();terminal.dispose();chimes.dispose();scene?.dispose();clearInterval(freshnessTimer);},{once:true});
