import {createJoinTimes} from './join-times.js';
import {memberGrowthSeries} from './member-series.mjs';
import {createStates} from './states.js';
import {summarize,chapterState,growthSeries,marketRows} from './model.mjs';
import {eyeSvg} from './eyes.js';
const $=id=>document.getElementById(id),fmt=n=>n.toLocaleString('en-US'),signed=n=>(n>0?'+':'')+fmt(n);
export function createTerminal({select,getSelected,openDirectory,scene}){
 document.querySelectorAll('.fomo-eyes').forEach(el=>el.innerHTML=eyeSvg());
 let lastSelected=null;let chapters=[],at=null,baseline=null,started=null,watch='top',chartMode='daily',chartDataset='chapters',memberHistory=null,selectedMemberDay=null,period=30,page=0,sort='joined',direction=-1,signal='all',type='all',query='',geography='all',focus=false,drift=true;
 const joinTimes=createJoinTimes();
 const states=createStates({onSelect(code){geography=code;page=0;renderMarket();}});
 let pins=new Set();try{const saved=JSON.parse(localStorage.getItem('fomo:pulse:watchlist')||'[]');if(Array.isArray(saved))pins=new Set(saved.filter(x=>typeof x==='string'));}catch{}
 function inspect(id){select(id);const stage=$('stage'),r=stage.getBoundingClientRect();if(r.bottom<80||r.top>innerHeight*.7)stage.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});}
 function delta(c){return baseline?c.joined-(baseline.get(c.id)??0):0;}
 function pin(id){pins.has(id)?pins.delete(id):pins.add(id);try{localStorage.setItem('fomo:pulse:watchlist',JSON.stringify([...pins]));}catch{}renderWatch();renderMarket();selection();}
 function selection(){const changedSelection=lastSelected!==getSelected();lastSelected=getSelected();const c=chapters.find(c=>c.id===getSelected());if(!c)return;$('pin-chapter').textContent=pins.has(c.id)?'★':'☆';$('pin-chapter').setAttribute('aria-pressed',String(pins.has(c.id)));$('selected-ratio').textContent=(c.joined/c.active*100).toFixed(1)+'%';const remaining=Math.max(0,Math.ceil(c.active*.8)-c.joined),rank=[...chapters].sort((a,b)=>b.joined-a.joined).findIndex(x=>x.id===c.id)+1;$('chapter-insight').textContent=c.joined>c.active?`Reported members exceed the active roster by ${fmt(c.joined-c.active)}. Both source counts are preserved.`:remaining===0?`Target reached. ${c.name} ranks #${rank} by members onboarded across ${chapters.length} chapter records.`:`${fmt(remaining)} more members to reach the 80% target. ${delta(c)>0?signed(delta(c))+' onboarded since this session began.':'Currently #'+rank+' by members onboarded.'}`;if(changedSelection)renderMarket();}
 $('pin-chapter').onclick=()=>{if(getSelected())pin(getSelected());};
 function renderWatch(){$('pin-count').textContent=pins.size;$('leaders').replaceChildren();const list=[...chapters].filter(c=>watch==='top'||pins.has(c.id)).sort((a,b)=>b.joined-a.joined).slice(0,5);if(!list.length){const p=document.createElement('p');p.className='muted';p.textContent='Pin a chapter with ☆ to keep its signal here.';$('leaders').append(p);}list.forEach((c,i)=>{const b=document.createElement('button');b.className='leader';b.setAttribute('aria-label',`${c.name}, ${c.school}, ${c.joined} onboarded`);const r=document.createElement('span');r.className='rank';r.textContent=watch==='top'?String(i+1).padStart(2,'0'):'★';const text=document.createElement('span'),name=document.createElement('b'),school=document.createElement('small'),n=document.createElement('span');name.textContent=c.name;school.textContent=c.shortSchool;n.className='count';n.textContent=fmt(c.joined);text.append(name,school);b.append(r,text,n);b.onclick=()=>inspect(c.id);$('leaders').append(b);});}
 for(const value of ['top','pinned'])$('watch-'+value).onclick=()=>{watch=value;for(const v of ['top','pinned']){$('watch-'+v).classList.toggle('active',v===value);$('watch-'+v).setAttribute('aria-pressed',String(v===value));}renderWatch();};
 function renderTicker(){$('market-ticker').replaceChildren();[...chapters].sort((a,b)=>b.joined-a.joined).slice(0,16).forEach(c=>{const b=document.createElement('button');b.className='ticker-item';b.setAttribute('aria-label',`Inspect ${c.name} at ${c.school}`);const name=document.createElement('strong'),school=document.createElement('span'),count=document.createElement('b');name.textContent=c.letters;school.textContent=c.shortSchool.replace('University of ','').replace('University','').trim();count.textContent=fmt(c.joined)+' JOINED';b.append(name,school,count);b.onclick=()=>inspect(c.id);$('market-ticker').append(b);});}
 function renderSignals(){const sum=summarize(chapters);$('signal-members').textContent=fmt(sum.joined);$('signal-ready').textContent=fmt(sum.ready);$('signal-near').textContent=fmt(chapters.filter(c=>chapterState(c)==='near').length);$('signal-today').textContent=fmt(chapters.filter(c=>c.registered===at?.slice(0,10)).length);const change=baseline?sum.joined-[...baseline.values()].reduce((a,b)=>a+b,0):0;$('signal-change').textContent=baseline?signed(change):'—';$('session-window').textContent=started?'since '+new Date(started).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'}):'Collecting observations';}
 function renderTypes(){const box=$('type-filters');box.replaceChildren();['all',...new Set(chapters.map(c=>c.type))].forEach(t=>{const b=document.createElement('button');b.textContent=t==='all'?'All sectors':t==='Student organization / club'?'Clubs':t==='Co-ed / other Greek org'?'Other Greek':t==='Professional fraternity'?'Professional':t;b.classList.toggle('active',type===t);b.setAttribute('aria-pressed',String(type===t));b.onclick=()=>{type=t;page=0;renderTypes();renderMarket();};box.append(b);});}
 function renderMarket(){
  const list=marketRows(chapters,{query,type,signal,geography,sort,direction,baseline:baseline||new Map(),today:at?.slice(0,10)}),pages=Math.max(1,Math.ceil(list.length/12));page=Math.min(page,pages-1);const visible=list.slice(page*12,page*12+12);$('market-rows').replaceChildren();$('market-result-count').textContent=list.length+' RECORDS';$('clear-filters').hidden=type==='all'&&signal==='all'&&geography==='all'&&!query;$('market-pagination').textContent=list.length?`${page*12+1}–${Math.min((page+1)*12,list.length)} of ${list.length} chapter records`:'No matching chapter records';$('market-prev').disabled=page===0;$('market-next').disabled=page>=pages-1;
  if(!visible.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=7;td.style.textAlign='center';td.textContent=signal==='changes'?'No count changes observed in this session yet.':'No matching chapters. Try another filter.';tr.append(td);$('market-rows').append(tr);}
  visible.forEach(c=>{const tr=document.createElement('tr');tr.classList.toggle('selected',c.id===getSelected());const cells=Array.from({length:7},()=>document.createElement('td'));const star=document.createElement('button');star.className='row-pin';star.textContent=pins.has(c.id)?'★':'☆';star.setAttribute('aria-pressed',String(pins.has(c.id)));star.setAttribute('aria-label',`Pin ${c.name} at ${c.school}`);star.onclick=()=>pin(c.id);cells[0].append(star);
   const chapter=document.createElement('button');chapter.className='row-chapter';const letters=document.createElement('span'),text=document.createElement('span'),name=document.createElement('strong'),school=document.createElement('small');letters.className='mini-symbol';letters.textContent=c.letters;name.textContent=c.name;school.textContent=c.school;text.append(name,school);chapter.append(letters,text);chapter.onclick=()=>inspect(c.id);cells[1].append(chapter);cells[2].textContent=fmt(c.joined);
   const ratio=c.joined/c.active*100,label=document.createElement('span'),bar=document.createElement('span'),fill=document.createElement('i');label.textContent=ratio.toFixed(1)+'%';bar.className='ratio-mini';fill.style.width=Math.min(100,ratio)+'%';bar.append(fill);cells[3].className='ratio-cell';cells[3].append(label,bar);cells[4].textContent=fmt(Math.max(0,Math.ceil(c.active*.8)-c.joined));const change=delta(c);cells[5].textContent=change?signed(change):'—';cells[5].className=change>0?'positive':change<0?'negative':'';const state=chapterState(c),tag=document.createElement('span');tag.className='state-tag '+state;tag.textContent={ready:'TARGET HIT',near:'APPROACHING',building:'BUILDING'}[state];cells[6].append(tag);tr.append(...cells);$('market-rows').append(tr);
  });
 }
 $('market-search').oninput=e=>{query=e.target.value;page=0;renderMarket();};$('market-prev').onclick=()=>{page--;renderMarket();};$('market-next').onclick=()=>{page++;renderMarket();};
 document.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{if(sort===b.dataset.sort)direction*=-1;else{sort=b.dataset.sort;direction=sort==='name'||sort==='remaining'?1:-1;}page=0;document.querySelectorAll('[data-sort]').forEach(el=>{el.parentElement.removeAttribute('aria-sort');if(el===b)el.parentElement.setAttribute('aria-sort',direction===1?'ascending':'descending');});renderMarket();});
 document.querySelectorAll('[data-signal]').forEach(b=>b.onclick=()=>{signal=b.dataset.signal;page=0;document.querySelectorAll('[data-signal]').forEach(el=>el.classList.toggle('active',el===b));renderMarket();document.querySelector('.market-section').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});});
 $('clear-filters').onclick=()=>{query='';type='all';signal='all';geography='all';states.reset();page=0;$('market-search').value='';document.querySelectorAll('[data-signal]').forEach(el=>el.classList.remove('active'));renderTypes();renderMarket();};
 function chart(){if(!at)return;const members=chartDataset==='members',data=members?memberGrowthSeries(memberHistory,at,period):growthSeries(chapters,at,period);$('chart-unavailable').hidden=!!data;$('growth-bars').hidden=!data;document.querySelector('.chart-foot').hidden=!data;$('growth-bars').setAttribute('aria-label',members?'Member signups by join date':'Chapter registrations by date');if(!data){$('growth-bars').replaceChildren();$('chart-value').textContent='—';$('chart-description').textContent='member join history unavailable';$('chart-period-label').textContent='MEMBER SIGNUPS';$('chart-hover').textContent='Waiting for the live export';return;}const values=data.map(d=>d[chartMode]),max=Math.max(1,...values),box=$('growth-bars');box.replaceChildren();$('chart-period-label').textContent=(members?'MEMBER SIGNUPS · ':'CHAPTER REGISTRATIONS · ')+(period==='all'?'ALL':period+'D');const total=chartMode==='daily'?values.reduce((a,b)=>a+b,0):values.at(-1);const reset=()=>{$('chart-value').textContent=fmt(total);$('chart-description').textContent=chartMode==='daily'?(members?'member signups in view':'chapter registrations in view'):(members?'total member signups through today':'chapter records in the network');$('chart-hover').textContent=members?'Hover to inspect · click to pin day':'Hover to inspect · click to filter';};reset();
  const hover=d=>{$('chart-value').textContent=fmt(d[chartMode]);$('chart-description').textContent=chartMode==='daily'?(members?'members who joined on this day':'chapters registered on this day'):(members?'total members through this day':'total chapters through this day');$('chart-hover').textContent=new Date(d.date+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'});};const drill=d=>{if(members){selectedMemberDay=selectedMemberDay===d.date?null:d.date;chart();return;}openDirectory();$('search').value=d.date;$('search').dispatchEvent(new Event('input'));};
  if(chartMode==='daily'){data.forEach((d,i)=>{const b=document.createElement('button');b.className='day-bar';b.style.height=Math.max(1,d.daily/max*100)+'%';b.style.animationDelay=i*.008+'s';b.setAttribute('aria-label',`${d.date}: ${d.daily} ${members?'member signups':'chapter registrations'}`);b.onmouseenter=()=>hover(d);b.onfocus=()=>hover(d);b.onblur=reset;b.onclick=()=>drill(d);if(members){b.classList.toggle('pinned-day',selectedMemberDay===d.date);b.setAttribute('aria-pressed',String(selectedMemberDay===d.date));}box.append(b);});}else{
   const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 800 137');svg.setAttribute('preserveAspectRatio','none');const points=data.map((d,i)=>[i/Math.max(1,data.length-1)*800,127-d.cumulative/max*116]);const path=points.map((p,i)=>(i?'L':'M')+p.join(',')).join(' '),area=document.createElementNS(ns,'path'),line=document.createElementNS(ns,'path');area.setAttribute('d',path+' L800,137 L0,137 Z');area.setAttribute('fill','#9272ed22');line.setAttribute('d',path);line.setAttribute('fill','none');line.setAttribute('stroke','#b697ff');line.setAttribute('stroke-width','2');line.setAttribute('vector-effect','non-scaling-stroke');svg.append(area,line);data.forEach((d,i)=>{const r=document.createElementNS(ns,'rect');r.setAttribute('x',Math.max(0,points[i][0]-400/data.length));r.setAttribute('width',800/data.length);r.setAttribute('height','137');r.setAttribute('class','chart-hotspot');r.setAttribute('role','button');r.setAttribute('tabindex','0');r.setAttribute('aria-label',`${d.date}: ${d.cumulative} cumulative ${members?'members':'chapters'}, ${d.daily} new`);r.onmouseenter=()=>hover(d);r.onfocus=()=>hover(d);r.onblur=reset;r.onclick=()=>drill(d);r.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();drill(d);}};svg.append(r);});box.append(svg);
  }
  const pinned=members&&data.find(d=>d.date===selectedMemberDay);if(pinned)hover(pinned);
  const scale=document.createElement('div');scale.className='chart-scale';[max,Math.round(max/2),0].forEach(n=>{const label=document.createElement('span');label.textContent=fmt(n);scale.append(label);});box.append(scale);box.onmouseleave=()=>pinned?hover(pinned):reset();const dateLabel=date=>new Date(date+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'});$('chart-start').textContent=dateLabel(data[0].date);$('chart-end').textContent=dateLabel(data.at(-1).date);document.querySelector('.chart-foot span:nth-child(2)').textContent=members?(chartMode==='daily'?'Member join dates · UTC · today is partial':'Cumulative member signups · UTC dates'):(chartMode==='daily'?'Chapter registrations · UTC dates':'Cumulative chapter records · UTC dates');
 }
 document.querySelectorAll('[data-dataset]').forEach(b=>b.onclick=()=>{chartDataset=b.dataset.dataset;selectedMemberDay=null;document.querySelectorAll('[data-dataset]').forEach(el=>{el.classList.toggle('active',el===b);el.setAttribute('aria-pressed',String(el===b));});chart();});
 document.querySelectorAll('[data-chart]').forEach(b=>b.onclick=()=>{chartMode=b.dataset.chart;document.querySelectorAll('[data-chart]').forEach(el=>{el.classList.toggle('active',el===b);el.setAttribute('aria-pressed',String(el===b));});chart();});document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{selectedMemberDay=null;period=b.dataset.period==='all'?'all':Number(b.dataset.period);document.querySelectorAll('[data-period]').forEach(el=>{el.classList.toggle('active',el===b);el.setAttribute('aria-pressed',String(el===b));});chart();});
 $('focus-chapter').onclick=()=>{focus=!focus;scene?.setFocus(focus);$('focus-chapter').setAttribute('aria-pressed',String(focus));$('focus-chapter').textContent=focus?'◎ Focused':'◎ Focus';};$('drift').onclick=()=>{drift=!drift;scene?.setDrift(drift);$('drift').setAttribute('aria-pressed',String(drift));};$('spread').oninput=e=>scene?.setSpread(Number(e.target.value)/100);
 let tapeHover=false,tapeDirection=1;const tape=$('market-ticker');tape.addEventListener('pointerenter',()=>tapeHover=true);tape.addEventListener('pointerleave',()=>tapeHover=false);tape.addEventListener('focusin',()=>tapeHover=true);tape.addEventListener('focusout',()=>tapeHover=false);const tapeTimer=setInterval(()=>{if(document.hidden||tapeHover||document.body.classList.contains('paused')||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const end=tape.scrollWidth-tape.clientWidth;if(end<=0)return;tape.scrollLeft+=tapeDirection*.8;if(tape.scrollLeft>=end-1)tapeDirection=-1;else if(tape.scrollLeft<=0)tapeDirection=1;},40);
 return {dispose(){clearInterval(tapeTimer);},selection,chart,renderWatch,update(snapshot){joinTimes.update(snapshot);const changed=at===null||JSON.stringify(chapters)!==JSON.stringify(snapshot.chapters),dateChanged=at?.slice(0,10)!==snapshot.updatedAt.slice(0,10);const historyChanged=JSON.stringify(memberHistory)!==JSON.stringify(snapshot.memberHistory);memberHistory=snapshot.memberHistory;chapters=snapshot.chapters;at=snapshot.updatedAt;if(!baseline&&!snapshot.stale){baseline=new Map(chapters.map(c=>[c.id,c.joined]));started=Date.now();}renderSignals();if(changed){states.update(chapters);renderTicker();renderTypes();renderWatch();renderMarket();}if(changed||dateChanged||historyChanged)chart();},arrival(){document.body.classList.add('glitch-signal');setTimeout(()=>document.body.classList.remove('glitch-signal'),1800);}};
}
