import fs from 'node:fs';
const offers=JSON.parse(fs.readFileSync(new URL('./offers.json',import.meta.url),'utf8'));
const companies=JSON.parse(fs.readFileSync(new URL('./companies.json',import.meta.url),'utf8'));
const companyById=new Map(companies.map(company=>[company.id,company]));
for(const offer of offers){if(!companyById.has(offer.companyId))throw Error('Unknown company for '+offer.id);}
const icons=JSON.parse(fs.readFileSync(new URL('./icons.json',import.meta.url),'utf8'));
const e=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const calendarPanel=`<section class="calendar-panel" aria-labelledby="calendar-editor-title"><h3 id="calendar-editor-title">Add your social calendar</h3><div id="calendar-drop" class="file-drop"><label for="calendar-file">Drop a file here or <span>choose a file</span></label><input id="calendar-file" type="file" accept=".pdf,.csv,.xlsx,.xls,.ics,.doc,.docx,.png,.jpg,.jpeg,.webp"><p>PDF, spreadsheet, calendar, document, or image · up to 10 MB</p></div><div id="calendar-attachment" hidden><strong id="calendar-file-name"></strong><div><button type="button" id="download-calendar" class="quiet-button">Download file</button><button type="button" id="remove-calendar" class="quiet-button">Remove file</button></div></div><p class="calendar-divider">or enter your event dates</p><div id="calendar-events"></div><button type="button" id="add-event" class="quiet-button">Add an event</button><p id="calendar-status" role="status" aria-live="polite"></p><p class="calendar-help">Your calendar saves privately with fomo. Submit this task when your file or event dates are ready for review.</p></section>`;
const cards=offers.map(o=>`<article class="task-card" data-task="${e(o.id)}" data-company="${e(o.companyId)}">
<details><summary class="card-trigger"><div class="card-top"><span class="task-context"><span class="company-tag">${companyById.get(o.companyId).badgeLogo?`<img src="${e(companyById.get(o.companyId).badgeLogo)}" alt="${e(companyById.get(o.companyId).name)}" width="28" height="18">`:e(companyById.get(o.companyId).name)}</span>${e(o.title)}</span><span class="status" data-status>Available</span></div>
<div class="reward"><div class="reward-icon">${icons[o.id]}</div><div><p class="kicker">${icons.gift}${e(o.perk.label)}</p><h2>${e(o.perk.title)}</h2><p class="description">${e(o.perk.description)}</p><ul class="perks">${o.perk.highlights.map(p=>`<li>${icons.check}${e(p)}</li>`).join('')}</ul></div></div>
<div class="card-toggle"><span class="when-closed">View task &amp; get started</span><span class="when-open">Hide task details</span>${icons.chevron}</div></summary><div class="task-body"><p class="review-feedback" role="status" hidden></p>
<div class="pitch"><span>WHAT YOU GET TO TELL THEM</span><blockquote>“${e(o.perk.pitch)}”</blockquote></div>
<h3>What to do</h3><div class="checklist">${o.tasks.map((t,j)=>`<section class="task-step"><label class="check-item"><input type="checkbox" data-check="${j}" ${o.id==='calendar'?'disabled':''}><span><strong>${e(t.title)}</strong><span>${e(t.detail)}</span><span class="task-win">${icons.gift}${e(o.perk.taskWins[j])}</span></span></label>${o.id==='calendar'?calendarPanel:''}<div class="step-editor" data-step-editor data-task-id="${e(o.id)}" data-step="${j}"><div class="step-editor-top"><span>STEP ${j+1}</span><span data-step-status>Not submitted</span></div><label for="step-${e(o.id)}-${j}">Your update for this step</label><textarea id="step-${e(o.id)}-${j}" data-step-notes rows="3" maxlength="6000" placeholder="${e(t.input||'Add details, names, or links for this step…')}"></textarea><label class="step-upload">Add files<input type="file" data-step-upload multiple accept=".pdf,.csv,.xlsx,.xls,.ics,.doc,.docx,.png,.jpg,.jpeg,.webp,.mp4,.mov"></label><p class="step-help">Up to 5 files, 10 MB each. For longer videos, paste a link above.</p><div data-step-files></div><p class="review-feedback" data-step-feedback hidden></p><button type="button" data-step-submit>Send step for review</button><p data-step-message role="status" aria-live="polite"></p></div></section>`).join('')}</div>
<form class="update-form"><label for="chapter-${e(o.id)}">Your chapter &amp; school</label><input id="chapter-${e(o.id)}" data-chapter type="text" maxlength="160" placeholder="e.g. Sigma Chi · University of Miami"><label for="notes-${e(o.id)}">Extra task notes (optional)</label><p>Keep any overall context here. Send each step for review above as you go.</p><textarea id="notes-${e(o.id)}" data-notes rows="4" maxlength="6000" placeholder="Names, links, and a quick update…"></textarea><p class="handoff">Drafts save automatically. Each step has its own review.</p><div class="task-bottom"><span data-count>0 of ${o.tasks.length} checklist items complete</span></div><p class="copy-status" role="status" aria-live="polite"></p></form>
</div></details></article>`).join('\n');
const html=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Campus Tasks</title><meta name="description" content="Choose campus tasks, build your team, and lead your campus with fomo."><meta name="robots" content="noindex,nofollow"><link rel="icon" href="/tasks/assets/favicon.svg"><link rel="stylesheet" href="/tasks/styles.css"><script type="module" src="/tasks/tasks.js"></script></head><body><noscript><p class="notice">Enable JavaScript to create your account or sign in to Campus Tasks.</p></noscript>
<dialog id="welcome" aria-labelledby="welcome-title"><form id="welcome-form"><h2 id="welcome-title">Campus Tasks</h2><div class="auth-tabs" role="group" aria-label="Account access"><button type="button" id="auth-create" aria-pressed="true">Create account</button><button type="button" id="auth-signin" aria-pressed="false">Sign in</button></div><p id="auth-context" class="welcome-intro">Create an account to choose campus tasks and track your work.</p><div id="signup-fields"><label for="member-name">Your name</label><input id="member-name" name="name" autocomplete="name" maxlength="100" required placeholder="First and last name"><label for="member-school">Your school</label><div class="school-picker"><input id="member-school" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-controls="school-options" aria-describedby="school-search-status" autocomplete="off" spellcheck="false" required disabled placeholder="Loading schools…"><ul id="school-options" role="listbox" aria-label="Matching schools" hidden></ul></div><p id="school-search-status" class="school-help" role="status" aria-live="polite">Type your school name or abbreviation.</p></div><label for="member-email">Email address</label><input id="member-email" name="email" type="email" autocomplete="email" maxlength="254" required placeholder="you@school.edu"><label for="member-password" id="password-label">Create a password</label><input id="member-password" name="password" type="password" autocomplete="new-password" minlength="12" maxlength="128" required aria-describedby="password-help"><p id="password-help" class="school-help">At least 12 characters. Use a password you don’t use elsewhere.</p><div id="password-confirm-field"><label for="member-password-confirm">Confirm password</label><input id="member-password-confirm" type="password" autocomplete="new-password" minlength="12" maxlength="128" required></div><p id="welcome-error" role="alert"></p><button id="auth-new-profile" type="button" class="quiet-button" hidden>Keep drafts &amp; create a new profile</button><button id="retry-schools" type="button" hidden>Retry loading schools</button><div class="welcome-actions"><button id="welcome-cancel" type="button" class="quiet-button" hidden>Cancel</button><button id="welcome-continue" type="submit" disabled>Enter my workspace</button></div></form></dialog>
<dialog id="campus-welcome" aria-labelledby="arrival-title" aria-describedby="arrival-description">
<div class="arrival-grid" aria-hidden="true"></div><div class="arrival-halo" aria-hidden="true"></div>
<div class="arrival-top"><span>campus tasks.</span></div>
<div class="arrival-content"><div class="arrival-eyes" aria-hidden="true"></div><p class="arrival-kicker">WELCOME TO CAMPUS TASKS</p><h2 id="arrival-title" data-arrival-name>You’re in.</h2><div class="arrival-campus"><span class="arrival-school-mark"><img data-arrival-logo alt="" width="32" height="32"></span><span data-arrival-school>Your campus</span><span class="arrival-verified" aria-label="Confirmed">✓</span></div><p id="arrival-description">Your campus. Your call.</p><p class="arrival-detail">Build your team.<br>Make something happen.</p></div>
<div class="arrival-bottom"><span>ONE CAMPUS. YOUR LEAD.</span><button type="button" data-arrival-enter autofocus>Enter my campus <span aria-hidden="true">↗</span></button></div><div class="arrival-progress" aria-hidden="true"></div>
</dialog>
<a class="skip-link" href="#opportunities">Skip to opportunities</a>
<header class="topbar" hidden><a href="/tasks" aria-label="Campus Tasks home" class="network-brand">campus<span>tasks</span><span class="brand-period">.</span></a><button id="change-profile" class="profile-button" type="button" hidden>Sign out</button></header>
<main hidden><section class="welcome-grid" aria-labelledby="campus-title"><div class="heading"><div class="campus-identity"><div class="school-logo-wrap" hidden><img id="school-logo" alt="" width="44" height="44"></div><div><p id="member-greeting">Your campus workspace</p><p id="pass-school">Personally selected.</p></div></div><h1 id="campus-title">Their capital.<br>Your campus. Your call.</h1><p class="lead">Choose your tasks. Build your team. Put company capital to work on your campus.</p><p class="campus-authority">You’re the one person on your campus in charge.</p></div>
<div class="career-preview"><div class="linkedin-card" aria-label="LinkedIn experience preview"><div class="linkedin-heading"><h3>Experience</h3><span class="linkedin-profile-icons" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 3v18M3 12h18"/></svg><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="m16.5 3.5 4 4M3 21l5-1L21 7a2.8 2.8 0 0 0-4-4L4 16l-1 5Z"/></svg></span></div><div class="linkedin-role"><img class="linkedin-company-icon" src="/tasks/assets/fomo-linkedin.svg" alt="fomo" width="72" height="72"><div class="linkedin-role-details"><h3>Campus Lead Intern</h3><p class="linkedin-company">fomo · Internship</p><p class="linkedin-meta linkedin-dates">Start date – Present</p><p class="linkedin-meta" id="experience-school">Your campus</p></div></div></div><div class="experience-unlock" hidden><button id="copy-experience" type="button" disabled hidden>Unlocks after 5 approved tasks</button><p id="experience-message" role="status"></p><textarea id="experience-copy-fallback" readonly aria-label="Your LinkedIn experience text" hidden></textarea></div></div></section>
<section class="opportunity-heading" id="opportunities" aria-labelledby="opportunities-title"><div><p class="eyebrow">YOUR WORKSPACE</p><h2 id="opportunities-title">Choose your next move.</h2><p>Every task is optional. Pick any, skip any, work in any order.</p></div></section>
<div class="company-strip" aria-label="Companies in your workspace">${companies.filter(c=>c.status==='active').map(c=>`<div class="active-company"><img src="${e(c.logo)}" alt="${e(c.name)}" width="63" height="20"><div><strong>${e(c.description)}</strong><span>${offers.filter(o=>o.companyId===c.id).length} opportunities</span></div><span class="company-live">Active company</span></div>`).join('')}<div class="future-companies"><span>More companies, same circle.</span><small>New partners will appear here when they launch.</small></div></div>
<div class="workspace-toolbar"><div class="task-filters" role="group" aria-label="Filter opportunities"><button type="button" data-filter="all" aria-pressed="true">All opportunities <span data-filter-count="all">5</span></button><button type="button" data-filter="active" aria-pressed="false">In progress <span data-filter-count="active">0</span></button><button type="button" data-filter="review" aria-pressed="false">In review <span data-filter-count="review">0</span></button><button type="button" data-filter="approved" aria-pressed="false">Approved <span data-filter-count="approved">0</span></button></div><details class="workspace-settings"><summary>Workspace tools</summary>
<div class="shared-controls"><button id="reload-progress" class="quiet-button" type="button" hidden>Load saved progress</button><p id="shared-message" role="status" aria-live="polite"></p></div></details></div><div class="board-caption"><strong id="completion-summary">Pick a task. See what you get.</strong><span id="save-status" role="status">Checklists save in this browser.</span></div><noscript><p class="notice">You can browse every task below. Turn on JavaScript to save checklists and copy updates.</p></noscript>
<div class="tasks-grid"><div class="offers">${cards}<div id="empty-opportunities" class="empty-opportunities" role="status" hidden><h3 id="empty-title">Your next move is waiting.</h3><p id="empty-description">Choose an opportunity and start with any step.</p><button type="button" id="show-all-tasks" class="quiet-button">Browse all opportunities</button></div></div><div class="bonus-column"><section class="trust-card" aria-labelledby="trust-title"><h2 id="trust-title">Grow your role.</h2><p>Strong work unlocks bigger tasks, larger budgets, and more freedom.</p></section><section class="experience-card" aria-labelledby="experience-title"><h2 id="experience-title">Build your team.</h2><p>Hire camera operators and content leads. They get paid work and internship experience alongside you.</p></section><section class="completion-bonus" aria-label="Five-task completion bonus"><p class="kicker">OPTIONAL FOMO BONUS</p><p class="completion-amount">$100</p><h2>Want to do all five?</h2><p>Complete all five tasks and get all five approved by fomo to earn an extra $100. Or just choose the tasks you want—the rest are always optional.</p><p id="bonus-progress">0 of 5 tasks completed</p><p id="bonus-next">Your choice. All five only if you want the bonus.</p></section><aside class="referral" aria-label="Optional referral bonus"><div class="referral-top">${icons.users}<span>REFERRAL BONUS</span></div><p class="bonus-amount">$50<span>–</span>$100</p><h2>Bring another chapter.<br>Get a bonus.</h2><p>Know someone in another chapter? Refer their chapter to fomo. Once they finish onboarding, you get <strong>$50–$100, depending on the chapter’s size.</strong></p><ol><li>Refer another chapter.</li><li>They finish onboarding.</li><li>You earn the bonus.</li></ol><div class="bonus-note">${icons.gift}<span>Extra money, anytime.<br>Optional, just like the other tasks.</span></div><details class="referral-form"><summary>Submit a chapter referral</summary><form id="chapter-referral"><label for="referral-notes">Chapter, school, and contact</label><textarea id="referral-notes" rows="4" maxlength="6000" placeholder="Who should fomo connect with?"></textarea><button type="submit">Submit referral</button><p id="referral-status" role="status"></p></form></details></aside></div></div>
<section class="circle-note" id="the-circle" aria-labelledby="circle-title"><div><p class="eyebrow">WHY YOU’RE HERE</p><h2 id="circle-title">The title didn’t get you here.<br>The way you move did.</h2></div><div><p>One point person on each selected campus, with company capital and opportunities to put behind their people. Work with the companies you like. Take the tasks you want. Pass on anything you don’t. We’re starting with fomo; more companies can join this same workspace later.</p><p class="circle-signoff">The access is yours. What you do with it is up to you.</p></div></section><footer><span>campus tasks.</span><p>Built by fomo</p></footer></main></body></html>`;
fs.writeFileSync(new URL('./index.html',import.meta.url),html+'\n');
console.log('Built current task offers.');
