import fs from 'node:fs';
const offers=JSON.parse(fs.readFileSync(new URL('./offers.json',import.meta.url),'utf8'));
const icons=JSON.parse(fs.readFileSync(new URL('./icons.json',import.meta.url),'utf8'));
const e=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cards=offers.map(o=>`<article class="task-card" data-task="${e(o.id)}">
<div class="card-top"><span>${e(o.title)}</span><span class="status" data-status>Available</span></div>
<div class="reward"><div class="reward-icon">${icons[o.id]}</div><div><p class="kicker">${icons.gift}${e(o.perk.label)}</p><h2>${e(o.perk.title)}</h2><p class="description">${e(o.perk.description)}</p><ul class="perks">${o.perk.highlights.map(p=>`<li>${icons.check}${e(p)}</li>`).join('')}</ul></div></div>
<details><summary><span class="when-closed">View task &amp; get started</span><span class="when-open">Hide task details</span>${icons.chevron}</summary><div class="task-body">
<div class="pitch"><span>WHAT YOU GET TO TELL THEM</span><blockquote>“${e(o.perk.pitch)}”</blockquote></div>
<h3>What to do</h3><div class="checklist">${o.tasks.map((t,j)=>`<label class="check-item"><input type="checkbox" data-check="${j}"><span><strong>${e(t.title)}</strong><span>${e(t.detail)}</span><span class="task-win">${icons.gift}${e(o.perk.taskWins[j])}</span></span></label>`).join('')}</div>
<form class="update-form"><label for="chapter-${e(o.id)}">Your chapter &amp; school</label><input id="chapter-${e(o.id)}" data-chapter type="text" maxlength="160" placeholder="e.g. Sigma Chi · University of Miami"><label for="notes-${e(o.id)}">Your update for fomo</label><p>${e(o.evidence)}</p><textarea id="notes-${e(o.id)}" data-notes rows="4" maxlength="6000" placeholder="Names, links, and a quick update…"></textarea><p class="handoff">Copy your update and send it to your fomo contact for review. Copying doesn’t submit it.</p><div class="task-bottom"><span data-count>0 of ${o.tasks.length} checklist items complete</span><button type="submit">Copy update for fomo</button></div><p class="copy-status" role="status" aria-live="polite"></p></form>
</div></details></article>`).join('\n');
const html=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Campus Tasks · fomo</title><meta name="description" content="Current fomo tasks and rewards for members who have onboarded a chapter. Pick any task, skip others, and work in any order."><meta name="robots" content="noindex,nofollow"><link rel="icon" href="/tasks/assets/favicon.svg"><link rel="stylesheet" href="/tasks/styles.css"><script type="module" src="/tasks/tasks.js"></script></head><body>
<header class="topbar"><a href="/tasks" aria-label="fomo campus tasks"><img src="/tasks/assets/fomo-lockup.svg" width="126" height="24" alt="fomo"></a><span>CAMPUS TASKS</span></header>
<main><div class="heading"><p class="eyebrow">CURRENT OPPORTUNITIES</p><h1>Own fomo on your campus</h1><p class="lead">Here’s what we’re offering right now. Pick the tasks you want, skip others, and do them in any order. More will be added.</p></div>
<div class="board-caption"><strong>Pick a task. See what you get.</strong><span id="save-status" role="status">Checklists save in this browser.</span></div><noscript><p class="notice">You can browse every task below. Turn on JavaScript to save checklists and copy updates.</p></noscript>
<div class="tasks-grid"><div class="offers">${cards}</div><aside class="referral" aria-label="Optional referral bonus"><div class="referral-top">${icons.users}<span>REFERRAL BONUS</span></div><p class="bonus-amount">$50<span>–</span>$100</p><h2>Bring another chapter.<br>Get a bonus.</h2><p>Know someone in another chapter? Refer their chapter to fomo. Once they finish onboarding, you get <strong>$50–$100, depending on the chapter’s size.</strong></p><ol><li>Refer another chapter.</li><li>They finish onboarding.</li><li>You earn the bonus.</li></ol><div class="bonus-note">${icons.gift}<span>Extra money, anytime.<br>Optional, just like the other tasks.</span></div></aside></div>
<div class="more-tasks"><h2>More tasks coming.</h2><p>These are the current offers. Come back to see what’s new.</p></div><footer><img src="/tasks/assets/fomo-wordmark.svg" width="63" height="20" alt="fomo"><p>For members who’ve fully onboarded a chapter.</p></footer></main></body></html>`;
fs.writeFileSync(new URL('./index.html',import.meta.url),html+'\n');
console.log('Built current task offers.');
