import {createCalendar} from './calendar.js';
import {PROFILE_KEY,LEGACY_KEY,normalizeName,profileMatch,loadProfiles,legacyProgress,readableAccent} from './profile.js';
const cards=[...document.querySelectorAll('[data-task]')],saveStatus=document.querySelector('#save-status');
const dialog=document.querySelector('#welcome'),form=document.querySelector('#welcome-form'),nameInput=document.querySelector('#member-name'),schoolInput=document.querySelector('#member-school'),error=document.querySelector('#welcome-error'),continueButton=document.querySelector('#welcome-continue'),cancelButton=document.querySelector('#welcome-cancel'),retryButton=document.querySelector('#retry-schools');
let storage;try{storage=window.localStorage;}catch{storage={getItem:()=>null,setItem:()=>{throw Error('Storage unavailable');},removeItem:()=>{}};}
let profiles=loadProfiles(storage),active=profiles.profiles.find(p=>p.id===profiles.activeId)||null,schools=[],loaded=false,loading=false;
const safeColor=(value,fallback)=>/^#[0-9a-f]{6}$/i.test(value)?value:fallback;
function write(){try{storage.setItem(PROFILE_KEY,JSON.stringify(profiles));saveStatus.textContent='Your name and progress are saved in this browser.';return true;}catch{saveStatus.textContent='Browser saving is unavailable. Keep a copy of your update.';return false;}}
function progress(card){const checks=[...card.querySelectorAll('[data-check]')],count=checks.filter(c=>c.checked).length,done=count===checks.length;card.querySelector('[data-count]').textContent=`${count} of ${checks.length} checklist items complete`;card.querySelector('[data-status]').textContent=done?'Completed':count?'In progress':'Available';card.classList.toggle('is-complete',done);const total=cards.filter(c=>c.classList.contains('is-complete')).length;document.querySelector('#completion-summary').textContent=total?`${total} ${total===1?'task':'tasks'} completed. Pick any other offer.`:'Pick a task. See what you get.';document.querySelector('#bonus-progress').textContent=`${total} of 5 tasks completed`;document.querySelector('#bonus-next').textContent=total===5?'All five checked off. Send your updates to fomo for review to claim your $100 bonus.':'Any order. All five for the bonus.';document.querySelector('.completion-bonus').classList.toggle('earned',total===5);}
function persist(){if(!active)return;active.progress=Object.fromEntries(cards.map(card=>[card.dataset.task,{checks:[...card.querySelectorAll('[data-check]')].map(c=>c.checked),chapter:card.querySelector('[data-chapter]').value,notes:card.querySelector('[data-notes]').value}]));write();}
function render(){if(!active)return;const school=active.school;document.body.classList.add('has-school');const primary=safeColor(school.primary,'#516AF6'),secondary=safeColor(school.secondary,'#221D4B'),ink=readableAccent(primary);for(const [k,v]of Object.entries({'--school-primary':primary,'--school-secondary':secondary,'--school-ink':ink,'--blue':ink}))document.body.style.setProperty(k,v);document.querySelector('#campus-title').textContent=`Own fomo @ ${school.name}`;document.title=`fomo @ ${school.name} · Campus Tasks`;document.querySelector('#member-greeting').textContent=`Welcome back, ${active.name}.`;document.querySelector('.campus-identity').hidden=false;const logo=document.querySelector('#school-logo');logo.hidden=!school.logo;if(school.logo&&/^\/[^/]/.test(school.logo)){logo.src=school.logo;logo.alt=`${school.name} logo`;logo.parentElement.style.background=school.logoBackground==='primary'?primary:'#fff';}else logo.hidden=true;logo.parentElement.hidden=logo.hidden;document.querySelector('#change-profile').hidden=false;for(const card of cards){const old=active.progress?.[card.dataset.task]||{};card.querySelectorAll('[data-check]').forEach((c,i)=>{c.checked=Array.isArray(old.checks)&&old.checks[i]===true;});card.querySelector('[data-chapter]').value=typeof old.chapter==='string'?old.chapter.slice(0,160):school.name;card.querySelector('[data-notes]').value=typeof old.notes==='string'?old.notes.slice(0,6000):'';card.querySelector('.copy-status').textContent='';card.querySelector('[data-copy-fallback]')?.remove();card.querySelector('details').open=false;progress(card);}const url=new URL(location.href);url.searchParams.set('school',school.id);history.replaceState(null,'',url);void calendar.render();saveStatus.textContent='Your name and progress are saved in this browser.';}
function openProfile(){error.textContent='';nameInput.value=active?.name||'';cancelButton.hidden=!active;if(loaded)schoolInput.value=active?.school.id||new URL(location.href).searchParams.get('school')||'';dialog.showModal();}
async function loadSchools(){if(loading)return;loading=true;retryButton.hidden=true;continueButton.disabled=true;schoolInput.disabled=true;error.textContent='';try{const r=await fetch('/api/task-schools');if(!r.ok)throw Error();const data=await r.json();if(!Array.isArray(data.schools)||!data.schools.length)throw Error();schools=data.schools.filter(s=>typeof s.id==='string'&&typeof s.name==='string');schoolInput.replaceChildren(new Option('Choose your school',''),...schools.map(s=>new Option(s.name,s.id)));loaded=true;schoolInput.disabled=false;continueButton.disabled=false;schoolInput.value=active?.school.id||new URL(location.href).searchParams.get('school')||'';if(active){const current=schools.find(s=>s.id===active.school.id);if(current){active.school=current;render();write();}else{if(!dialog.open)openProfile();schoolInput.value='';error.textContent='Your saved school is no longer in the current list. Choose a listed school to continue.';}}}catch{error.textContent='We couldn’t load the school list. Please try again.';retryButton.hidden=false;schoolInput.replaceChildren(new Option('School list unavailable',''));}finally{loading=false;}}
form.addEventListener('submit',event=>{event.preventDefault();const name=normalizeName(nameInput.value),school=schools.find(s=>s.id===schoolInput.value);if(!name||!school){error.textContent='Enter your name and choose a school from the list.';return;}let profile=profileMatch(profiles.profiles,name,school.id);const first=profiles.profiles.length===0;if(!profile){profile={id:crypto.randomUUID(),name,school,progress:first?legacyProgress(storage):{}};profiles.profiles.push(profile);}profile.name=name;profile.school=school;active=profile;profiles.activeId=active.id;render();const saved=write();if(saved&&first)storage.removeItem(LEGACY_KEY);dialog.close();});
dialog.addEventListener('cancel',event=>{if(!active)event.preventDefault();});cancelButton.addEventListener('click',()=>dialog.close());retryButton.addEventListener('click',()=>void loadSchools());document.querySelector('#change-profile').addEventListener('click',()=>{openProfile();if(!loaded)void loadSchools();});
for(const card of cards){card.addEventListener('input',()=>{progress(card);persist();});card.querySelector('form').addEventListener('submit',async event=>{event.preventDefault();const chapter=card.querySelector('[data-chapter]'),notes=card.querySelector('[data-notes]'),status=card.querySelector('.copy-status');if(!active){openProfile();return;}if(!chapter.value.trim()){status.textContent='Add your chapter and school before copying.';chapter.focus();return;}if(!notes.value.trim()&&!(card.dataset.task==='calendar'&&calendar.text())){status.textContent='Add your names, links, and update before copying.';notes.focus();return;}const checklist=[...card.querySelectorAll('.check-item')].map(label=>`${label.querySelector('input').checked?'[x]':'[ ]'} ${label.querySelector('strong').textContent}`).join('\n');const update=`fomo task: ${card.querySelector('.card-top>span').textContent}\nName: ${active.name}\nSchool: ${active.school.name}\nChapter & school: ${chapter.value.trim()}\n\n${checklist}\n\n${notes.value.trim()}${card.dataset.task==='calendar'?'\n\n'+calendar.text():''}`;try{await navigator.clipboard.writeText(update);status.textContent='Copied. Send this update to your fomo contact for review.';}catch{let fallback=card.querySelector('[data-copy-fallback]');if(!fallback){fallback=document.createElement('textarea');fallback.dataset.copyFallback='';fallback.readOnly=true;fallback.setAttribute('aria-label','Update to copy manually');card.querySelector('form').append(fallback);}fallback.value=update;fallback.focus();fallback.select();status.textContent='Select and copy the update below, then send it to your fomo contact.';}});}
const calendar=createCalendar({getProfile:()=>active,save:persist,onProgress:progress});
if(active)render();else openProfile();void loadSchools();
