import {showCampusWelcome} from './welcome-reveal.js';
import {approvedFomoTasks,experienceText} from './experience.js';
import {newPasswordSalt,passwordProof} from './password.js';
import {opportunityStatus,opportunityCounts} from './network.js';
import {createStepEditors} from './steps.js';
import {createSharedTasks,taskRequest} from './shared.js';
import {createSchoolPicker} from './school-search.js';
import {createCalendar} from './calendar.js';
import {PROFILE_KEY,normalizeName,loadProfiles,legacyProgress,readableAccent,savedChecks} from './profile.js';
const cards=[...document.querySelectorAll('[data-task]')],saveStatus=document.querySelector('#save-status');
const dialog=document.querySelector('#welcome'),form=document.querySelector('#welcome-form'),nameInput=document.querySelector('#member-name'),schoolInput=document.querySelector('#member-school'),error=document.querySelector('#welcome-error'),continueButton=document.querySelector('#welcome-continue'),cancelButton=document.querySelector('#welcome-cancel'),retryButton=document.querySelector('#retry-schools');
const schoolPicker=createSchoolPicker(schoolInput,document.querySelector('#school-options'),document.querySelector('#school-search-status'));
let authenticated=false,authMode='signup',authBusy=false;
const emailInput=document.querySelector('#member-email'),passwordInput=document.querySelector('#member-password'),passwordConfirm=document.querySelector('#member-password-confirm');
let currentFilter='all';
function paintBoard(){
 const counts=opportunityCounts(active,cards.map(card=>card.dataset.task));
 document.querySelectorAll('[data-filter-count]').forEach(el=>el.textContent=counts[el.dataset.filterCount]);
 for(const card of cards){const status=opportunityStatus(active,card.dataset.task);card.hidden=currentFilter!=='all'&&status!==currentFilter;card.querySelector('[data-status]').textContent=({approved:'Approved',review:'In review',active:'In progress',available:'Available'})[status];}
 document.querySelectorAll('[data-filter]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.filter===currentFilter)));
 const empty=!cards.some(card=>!card.hidden);
 document.querySelector('#empty-opportunities').hidden=!empty;
 const messages={active:['Your next move is waiting.','Start any opportunity. Your drafts and steps will appear here.'],review:['Nothing waiting on review.','Send a step when it’s ready. You can keep working while fomo reviews it.'],approved:['Good things take follow-through.','Your approved opportunities will appear here after fomo reviews your work.']};
 if(empty){const [title,description]=messages[currentFilter]||messages.active;document.querySelector('#empty-title').textContent=title;document.querySelector('#empty-description').textContent=description;}
}
function filterBoard(value){currentFilter=value;paintBoard();}
for(const button of document.querySelectorAll('[data-filter]'))button.addEventListener('click',()=>filterBoard(button.dataset.filter));
document.querySelector('#show-all-tasks').addEventListener('click',()=>{filterBoard('all');document.querySelector('[data-filter="all"]').focus();});
let storage;try{storage=window.localStorage;}catch{storage={getItem:()=>null,setItem:()=>{throw Error('Storage unavailable');},removeItem:()=>{}};}
let profiles=loadProfiles(storage),active=profiles.profiles.find(p=>p.id===profiles.activeId)||null,schools=[],loaded=false,loading=false;
const safeColor=(value,fallback)=>/^#[0-9a-f]{6}$/i.test(value)?value:fallback;
function write(){try{storage.setItem(PROFILE_KEY,JSON.stringify(profiles));saveStatus.textContent='Your name and progress are saved in this browser.';return true;}catch{saveStatus.textContent='Browser saving is unavailable. Keep a copy of your update.';return false;}}
function progress(card){const checks=[...card.querySelectorAll('[data-check]')],count=checks.filter(c=>c.checked).length,done=count===checks.length;card.querySelector('[data-count]').textContent=`${count} of ${checks.length} checklist items complete`;card.querySelector('[data-status]').textContent=done?'Completed':count?'In progress':'Available';card.classList.toggle('is-complete',done);const total=cards.filter(c=>c.classList.contains('is-complete')).length;document.querySelector('#completion-summary').textContent=total?`${total} ${total===1?'task':'tasks'} checked off. Choose what’s next.`:'Pick a task. See what you get.';document.querySelector('#bonus-progress').textContent=`${total} of 5 tasks completed`;document.querySelector('#bonus-next').textContent=total===5?'All five checked off. Send your updates to fomo for review to claim your $100 bonus.':'Your choice. All five only if you want the bonus.';document.querySelector('.completion-bonus').classList.toggle('earned',total===5);}
function persist(){if(!active||!authenticated)return;active.progress={...active.progress,...Object.fromEntries(cards.map(card=>[card.dataset.task,{checks:[...card.querySelectorAll('[data-check]')].map(c=>c.checked),chapter:card.querySelector('[data-chapter]').value,notes:card.querySelector('[data-notes]').value}]))};write();shared.schedule();paintBoard();}
function render(){if(!active||!authenticated)return;document.querySelector('main').hidden=false;document.querySelector('.topbar').hidden=false;const school=active.school;document.body.classList.add('has-school');const primary=safeColor(school.primary,'#516AF6'),secondary=safeColor(school.secondary,'#221D4B'),ink=readableAccent(primary);for(const [k,v]of Object.entries({'--school-primary':primary,'--school-secondary':secondary,'--school-ink':ink,'--blue':ink}))document.body.style.setProperty(k,v);document.querySelector('#campus-title').textContent=`Your campus. Your call, ${active.name.split(' ')[0]}.`;document.title=`${school.name} · Campus Tasks`;document.querySelector('#member-greeting').textContent=active.name;document.querySelector('#pass-school').textContent=school.name;document.querySelector('#experience-school').textContent=school.name;document.querySelector('.campus-identity').hidden=false;const logo=document.querySelector('#school-logo');logo.hidden=!school.logo;if(school.logo&&/^\/[^/]/.test(school.logo)){logo.src=school.logo;logo.alt=`${school.name} logo`;logo.parentElement.style.background=school.logoBackground==='primary'?primary:'#fff';}else logo.hidden=true;logo.parentElement.hidden=logo.hidden;document.querySelector('#change-profile').hidden=false;for(const card of cards){const old=active.progress?.[card.dataset.task]||{},checks=savedChecks(card.dataset.task,old.checks);card.querySelectorAll('[data-check]').forEach((c,i)=>{c.checked=checks[i]===true;});card.querySelector('[data-chapter]').value=typeof old.chapter==='string'?old.chapter.slice(0,160):school.name;card.querySelector('[data-notes]').value=typeof old.notes==='string'?old.notes.slice(0,6000):'';card.querySelector('.copy-status').textContent='';card.querySelector('[data-copy-fallback]')?.remove();card.querySelector('details').open=false;progress(card);}const url=new URL(location.href);url.searchParams.set('school',school.id);history.replaceState(null,'',url);void calendar.render();steps.restore();saveStatus.textContent='Your draft is saved in this browser.';paintShared();}
function setAuthMode(mode){authMode=mode;const signup=mode==='signup';document.querySelector('#signup-fields').hidden=!signup;document.querySelector('#password-confirm-field').hidden=!signup;nameInput.required=signup;schoolInput.required=signup;passwordConfirm.required=signup;passwordConfirm.disabled=!signup;passwordInput.minLength=signup?12:1;passwordInput.autocomplete=signup?'new-password':'current-password';document.querySelector('#password-label').textContent=signup?'Create a password':'Password';document.querySelector('#password-help').textContent=signup?'At least 12 characters. Use a password you don’t use elsewhere.':'Use the password you created for Campus Tasks. If you need help getting back in, contact your fomo point of contact.';document.querySelector('#auth-context').textContent=signup?(active?.token&&!active.account?'Secure your existing profile. Your progress stays with you.':'Create an account to choose campus tasks and track your work.'):'Sign in to pick up where you left off.';continueButton.textContent=signup?'Create account & enter':'Sign in';continueButton.disabled=authBusy||(signup&&!loaded);document.querySelector('#auth-create').setAttribute('aria-pressed',String(signup));document.querySelector('#auth-signin').setAttribute('aria-pressed',String(!signup));error.textContent='';}
function openProfile(){error.textContent='';nameInput.value=active?.name||'';cancelButton.hidden=true;document.querySelector('main').hidden=true;document.querySelector('.topbar').hidden=true;setAuthMode(active?.account?'signin':'signup');if(loaded)schoolPicker.select(active?.school.id||new URL(location.href).searchParams.get('school')||'');if(!dialog.open)dialog.showModal();}
async function loadSchools(){if(loading)return;loading=true;retryButton.hidden=true;continueButton.disabled=authMode==='signup';schoolInput.disabled=true;error.textContent='';try{const r=await fetch('/api/task-schools');if(!r.ok)throw Error();const data=await r.json();if(!Array.isArray(data.schools)||!data.schools.length)throw Error();schools=data.schools.filter(s=>typeof s.id==='string'&&typeof s.name==='string');schoolPicker.setSchools(schools);schoolInput.placeholder='School name or abbreviation, e.g. SDSU';loaded=true;schoolInput.disabled=false;continueButton.disabled=authBusy;schoolPicker.select(active?.school.id||new URL(location.href).searchParams.get('school')||'');if(active){const current=schools.find(s=>s.id===active.school.id);if(current){active.school=current;render();write();}else if(authenticated){if(!dialog.open)openProfile();schoolPicker.select('');error.textContent='Your saved school is no longer in the current list. Choose a listed school to continue.';}}}catch{error.textContent='We couldn’t load the school list. Please try again.';retryButton.hidden=false;schoolInput.placeholder='School list unavailable';}finally{loading=false;}}
document.querySelector('#auth-new-profile').addEventListener('click',()=>{if(active&&!active.account){delete active.token;delete active.cloud;active.dirty=true;write();}history.replaceState(null,'',location.pathname);document.querySelector('#auth-new-profile').hidden=true;error.textContent='Your browser drafts will be copied into your new account.';});
document.querySelector('#auth-create').addEventListener('click',()=>{setAuthMode('signup');if(!loaded)void loadSchools();});
document.querySelector('#auth-signin').addEventListener('click',()=>setAuthMode('signin'));
form.addEventListener('submit',async event=>{
 event.preventDefault();if(authBusy)return;
 const email=emailInput.value.trim().toLowerCase(),password=passwordInput.value,signup=authMode==='signup';
 const name=normalizeName(nameInput.value),school=schools.find(s=>s.id===schoolPicker.value);
 if(signup&&(!name||!school)){error.textContent='Enter your name and choose a listed school.';return;}
 if(signup&&(password.length<12||password!==passwordConfirm.value)){error.textContent=password.length<12?'Use at least 12 characters for your password.':'Your passwords don’t match.';return;}
 authBusy=true;continueButton.disabled=true;continueButton.textContent=signup?'Creating your account…':'Signing in…';error.textContent='';
 try{
  let out;
  if(signup){const salt=newPasswordSalt(),proof=await passwordProof(password,salt);const legacyToken=active?.token&&!active.account?active.token:new URLSearchParams(location.hash.slice(1)).get('profile')||'';out=await taskRequest(legacyToken,'signup',{email,name,schoolId:school.id,salt,proof});}
  else{const challenge=await taskRequest('','challenge',{email});const proof=await passwordProof(password,challenge.salt);out=await taskRequest('','login',{email,proof});}
  const previous=signup&&active&&!active.account?active:profiles.profiles.find(p=>p.cloud?.member?.id===out.member.id);
  const profile=previous||{id:crypto.randomUUID(),progress:signup&&profiles.profiles.length===0?legacyProgress(storage):{}};
  profile.token=out.token;profile.account=true;profile.email=email;profile.name=out.member.name;profile.school=schools.find(s=>s.id===out.member.schoolId)||{id:out.member.schoolId,name:out.member.schoolName};
  if(!previous){profile.cloud={member:out.member,tasks:out.tasks,steps:out.steps||[]};profile.dirty=signup&&Object.keys(profile.progress).length>0;profiles.profiles.push(profile);}
  active=profile;profiles.activeId=profile.id;authenticated=true;passwordInput.value='';passwordConfirm.value='';write();history.replaceState(null,'',location.pathname);dialog.close();render();if(signup)showCampusWelcome(profile);void shared.start(profile);
 }catch(e){error.textContent=e.message||'Couldn’t sign in. Please try again.';document.querySelector('#auth-new-profile').hidden=e.code!=='LEGACY_NOT_FOUND';}
 finally{authBusy=false;continueButton.disabled=authMode==='signup'&&!loaded;continueButton.textContent=authMode==='signup'?'Create account & enter':'Sign in';}
});
dialog.addEventListener('cancel',event=>event.preventDefault());retryButton.addEventListener('click',()=>void loadSchools());
document.querySelector('#change-profile').addEventListener('click',async()=>{
 if(authBusy||!active)return;authBusy=true;const button=document.querySelector('#change-profile');button.disabled=true;
 try{await taskRequest(active.token,'logout');profiles.profiles=profiles.profiles.filter(p=>p.id!==active.id);profiles.activeId=null;authenticated=false;active=null;write();emailInput.value='';nameInput.value='';passwordInput.value='';passwordConfirm.value='';openProfile();setAuthMode('signin');}
 catch(e){sharedMessage('Couldn’t sign out. Please try again.',true);}finally{authBusy=false;button.disabled=false;continueButton.disabled=authMode==='signup'&&!loaded;}
});
function paintShared(){if(!active)return;const careerApproved=approvedFomoTasks(active);const careerReady=careerApproved===5;document.querySelector('#experience-progress').textContent=careerReady?'Unlocked · All 5 fomo tasks approved':`Preview · ${careerApproved} of 5 tasks approved`;document.querySelector('#copy-experience').disabled=!careerReady;document.querySelector('#copy-experience').textContent=careerReady?'Copy LinkedIn experience':'Unlocks after 5 approved tasks';document.querySelector('.linkedin-card').classList.toggle('unlocked',careerReady);document.querySelector('#reload-progress').hidden=!active.cloud;for(const card of cards){const task=active.cloud?.tasks.find(t=>t.taskId===card.dataset.task);const locked=task?.status==='approved';if(task){card.querySelector('[data-status]').textContent=({draft:'In progress',submitted:'In review',approved:'Approved',changes_requested:'Changes requested'})[task.status];const feedback=card.querySelector('.review-feedback');feedback.hidden=!task.feedback;feedback.textContent=task.feedback?'fomo feedback: '+task.feedback:'';}card.querySelectorAll('input:not([data-step-upload]),textarea:not([data-step-notes]),button:not([data-step-submit])').forEach(el=>el.disabled=(locked&&el.id!=='download-calendar')||(card.dataset.task==='calendar'&&el.matches('[data-check]')));}const approved=(active.cloud?.tasks||[]).filter(t=>t.taskId!=='referral'&&t.status==='approved').length;document.querySelector('#bonus-progress').textContent=approved+' of 5 tasks approved';document.querySelector('.completion-bonus').classList.toggle('earned',approved===5);document.querySelector('#completion-summary').textContent=approved?approved+' of 5 tasks approved. Choose any offer.':'Your opportunities. Your choice.';document.querySelector('#bonus-next').textContent=active.cloud?.member.bonusPaidAt?'Your $100 bonus is marked paid.':approved===5?'All five approved. Your $100 bonus is ready for fomo to pay.':'Optional extra: all five approved earns $100. Pick and choose freely.';document.querySelector('#referral-notes').value=active.progress?.referral?.notes||'';const referral=active.cloud?.tasks.find(t=>t.taskId==='referral');document.querySelector('#referral-status').textContent=referral?(referral.paidAt?'Referral reward marked paid.':referral.status.replaceAll('_',' '))+(referral.feedback?' — '+referral.feedback:''):'';steps.paint();paintBoard();}
function sharedMessage(text,bad=false){document.querySelector('#shared-message').textContent=text;document.querySelector('#shared-message').classList.toggle('error',bad);saveStatus.textContent=bad?'Draft kept in this browser. Shared save needs attention.':text;}
for(const card of cards){card.addEventListener('input',event=>{if(event.target.closest('[data-step-editor]'))return;progress(card);persist();});card.querySelector('form').addEventListener('submit',event=>event.preventDefault());}
const calendar=createCalendar({getProfile:()=>authenticated?active:null,save:persist,onProgress:card=>{progress(card);paintShared();},downloadShared:id=>shared.download(id)});
const shared=createSharedTasks({getProfile:()=>authenticated?active:null,write,onState:paintShared,onRestore:()=>{render();paintShared();},onMessage:sharedMessage});
const steps=createStepEditors({getProfile:()=>authenticated?active:null,write,shared,onChange:paintShared});
document.querySelector('#reload-progress').addEventListener('click',async()=>{if(!confirm('Load the version saved with fomo? Any unsaved changes in this browser will be replaced.'))return;try{await shared.reload();}catch(error){sharedMessage(error.message,true);}});
document.querySelector('#referral-notes').addEventListener('input',event=>{if(!active)return;active.progress.referral={checks:[false],chapter:active.school.name,notes:event.target.value};shared.schedule();});
document.querySelector('#chapter-referral').addEventListener('submit',async event=>{event.preventDefault();if(!active)return;active.progress.referral={checks:[true],chapter:active.school.name,notes:document.querySelector('#referral-notes').value};write();try{await shared.submit('referral');}catch(error){sharedMessage(error.message,true);}});
document.querySelector('#copy-experience').addEventListener('click',async()=>{if(!authenticated||approvedFomoTasks(active)!==5)return;const text=experienceText(active.school.name);try{await navigator.clipboard.writeText(text);document.querySelector('#experience-message').textContent='Copied. Add your actual dates and adjust the details to match your work.';}catch{const field=document.querySelector('#experience-copy-fallback');field.hidden=false;field.value=text;field.select();document.querySelector('#experience-message').textContent='Select and copy your experience below.';}});
// Validate the session before exposing any saved profile or task workspace.
openProfile();
void (async()=>{
 await loadSchools();
 if(active?.account&&active.token){try{await taskRequest(active.token,'get');authenticated=true;dialog.close();render();void shared.start(active);}catch(e){error.textContent=e.code==='AUTH_REQUIRED'?'Sign in to continue.':e.message;}}
 paintBoard();
})();
window.addEventListener('campus-auth-required',event=>{if(event.detail?.token!==active?.token)return;authenticated=false;openProfile();});
