import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {harness} from './support/internal-harness.mjs';import {passwordProof,newPasswordSalt} from '../tasks/password.js';
const token=()=>randomUUID()+randomUUID();
function fixture(){const h=harness();h.ctx.ctSchool=id=>({id,name:'Example University'});const call=(action,p={})=>h.ctx.campusTasksApi({action,...p});const data={name:'Campus Test',email:'campus-test@example.com',schoolId:'example',salt:'a'.repeat(32),proof:'b'.repeat(64)};return{h,call,data};}
test('passwordless joins and legacy sessions cannot read or write tasks',()=>{const {h,call}=fixture(),legacy=token();const old=h.ctx.ctJoin({_taskToken:legacy,name:'Legacy',schoolId:'example'});assert(old.ok);assert.equal(call('join',{_taskToken:token(),name:'New',schoolId:'example'}).code,'PASSWORD_SETUP_REQUIRED');for(const action of ['get','save','upload','file','submitstep'])assert.equal(call(action,{_taskToken:legacy}).code,'PASSWORD_SETUP_REQUIRED');});
test('account setup protects existing progress, invalidates old links, and refuses account takeover',()=>{const {h,call,data}=fixture(),legacy=token();const old=h.ctx.ctJoin({_taskToken:legacy,name:'Legacy',schoolId:'example'});h.ctx.ctWrite('progress',h.ctx.CT_TASKS,{id:old.member.id+':host',memberId:old.member.id,taskId:'host',status:'draft',draft:JSON.stringify({notes:'Existing private work'}),revision:1});const created=call('signup',{...data,_taskToken:legacy});assert(created.ok,created.error);assert.equal(created.member.id,old.member.id);assert.equal(created.tasks[0].draft.notes,'Existing private work');assert.equal(call('get',{_taskToken:legacy}).code,'AUTH_REQUIRED');assert(call('get',{_taskToken:created.token}).ok);assert(!call('signup',{...data,email:'attacker@example.com',_taskToken:legacy}).ok);assert.equal(call('signup',data).code,'ACCOUNT_EXISTS');const publicData=JSON.stringify(call('get',{_taskToken:created.token}));assert(!/verifierHash|tokenHash|salt|campus-test@example/.test(publicData));});
test('login requires the proof, rate limits failures, and logout revokes only its own session',()=>{const {h,call,data}=fixture();const created=call('signup',data);assert(created.ok);assert.equal(call('challenge',{email:data.email}).salt,data.salt);const logged=call('login',{email:data.email,proof:data.proof});assert(logged.ok);assert(call('logout',{_taskToken:logged.token}).ok);assert.equal(call('get',{_taskToken:logged.token}).code,'AUTH_REQUIRED');assert(call('get',{_taskToken:created.token}).ok);for(let i=0;i<10;i++)assert.equal(call('login',{email:data.email,proof:'c'.repeat(64)}).code,'INVALID_LOGIN');assert.equal(call('login',{email:data.email,proof:data.proof}).code,'RATE_LIMIT');const records=h.ctx.ctRows('sessions',h.ctx.CT_SESSIONS);assert(!JSON.stringify(records).includes(created.token));});
test('expired and made-up sessions fail closed, credentials are excluded from operator listings',()=>{const {h,call,data}=fixture(),created=call('signup',data);const session=h.ctx.ctRows('sessions',h.ctx.CT_SESSIONS)[0];session.expiresAt=1;h.ctx.ctWrite('sessions',h.ctx.CT_SESSIONS,session);assert.equal(call('get',{_taskToken:created.token}).code,'AUTH_REQUIRED');assert.equal(call('get',{_taskToken:token()}).code,'AUTH_REQUIRED');const listing=call('list',{_session:h.login('Milo')});assert(listing.ok);assert(!/verifierHash|tokenHash|salt|campus-test@example/.test(JSON.stringify(listing)));});
test('Web Crypto password proof is deterministic for login and varies by password and salt',async()=>{const salt=newPasswordSalt();assert.match(salt,/^[a-f0-9]{32}$/);const proof=await passwordProof('Synthetic test password only',salt);assert.equal(proof,await passwordProof('Synthetic test password only',salt));assert.notEqual(proof,await passwordProof('Different synthetic password',salt));assert.notEqual(proof,await passwordProof('Synthetic test password only',newPasswordSalt()));const {call,data}=fixture();const created=call('signup',{...data,salt,proof});assert(created.ok);assert(call('login',{email:data.email,proof:await passwordProof('Synthetic test password only',call('challenge',{email:data.email}).salt)}).ok);});
