import test from 'node:test';import assert from 'node:assert/strict';import{randomUUID}from'node:crypto';import{harness}from'./support/internal-harness.mjs';
const token=()=>randomUUID()+randomUUID();
function setup(){const h=harness();h.ctx.ctSchool=id=>{if(id!=='duke')throw Error('Choose a school currently listed on fomo campus.');return{id:'duke',name:'Duke University'};};const call=(t,action,p={})=>h.ctx.campusTasksApi({_taskToken:t,action,...p});const join=(t=token(),name='Alex')=>{const out=call('','signup',{name,schoolId:'duke',email:t.replaceAll('-','')+'@example.com',salt:'a'.repeat(32),proof:'b'.repeat(64)});return{token:out.token,out};};return{h,call,join,admin:(action,p={},who='Milo')=>h.ctx.campusTasksApi({_session:h.login(who),action,...p})};}
const draft=(task,notes='Creator profile and evidence')=>({checks:Array(task==='dinner'?5:task==='calendar'||task==='referral'?1:2).fill(true),chapter:'Example Chapter',notes,...(task==='calendar'?{calendar:{events:[{title:'Mixer',date:'2026-10-31',time:'19:00'}],file:null}}:{})});
test('profiles are idempotent, private, and bound to unguessable tokens rather than name and school',()=>{const{call,join,admin}=setup(),a=join(),b=join();assert(a.out.ok);assert.notEqual(a.out.member.id,b.out.member.id);assert.equal(call(a.token,'join',{name:'Impersonator',schoolId:'wrong'}).code,'PASSWORD_SETUP_REQUIRED');assert.equal(call(token(),'get').ok,false);assert.equal(call('','list').code,'FORBIDDEN');assert.equal(admin('list',{},'Bijan').code,'FORBIDDEN');assert(!JSON.stringify(admin('list')).includes('tokenHash'));assert.equal(call(token(),'join',{name:'Someone',schoolId:'made-up'}).ok,false);});
test('drafts, submissions, review revisions and change requests remain distinct',()=>{const{call,join,admin}=setup(),a=join();let r=call(a.token,'save',{taskId:'host',revision:0,draft:draft('host')});assert.equal(r.tasks[0].status,'draft');assert.equal(admin('review',{memberId:a.out.member.id,taskId:'host',revision:1,decision:'approved'}).ok,false);r=call(a.token,'submit',{taskId:'host',revision:1,draft:draft('host')});assert.equal(r.tasks[0].status,'submitted');assert.equal(call(a.token,'submit',{taskId:'host',revision:1,draft:draft('host')}).tasks[0].revision,2);assert.equal(admin('review',{memberId:a.out.member.id,taskId:'host',revision:1,decision:'approved'}).ok,false);r=call(a.token,'save',{taskId:'host',revision:2,draft:draft('host','Edited after submitting')});assert.equal(r.tasks[0].status,'draft');assert.equal(r.tasks[0].snapshot.notes,'Creator profile and evidence');assert.equal(admin('review',{memberId:a.out.member.id,taskId:'host',revision:3,decision:'approved'}).ok,false);r=call(a.token,'submit',{taskId:'host',revision:3,draft:draft('host','Edited after submitting')});assert.equal(admin('review',{memberId:a.out.member.id,taskId:'host',revision:4,decision:'changes_requested',feedback:''}).ok,false);assert.equal(admin('review',{memberId:a.out.member.id,taskId:'host',revision:4,decision:'changes_requested',feedback:'Add video links'}).ok,true);assert.equal(call(a.token,'get').tasks[0].feedback,'Add video links');assert.equal(call(a.token,'save',{taskId:'host',revision:4,draft:draft('host','Stale')}).code,'CONFLICT');});
test('only admins approve tasks and all five approvals gate the bonus payment record',()=>{const{call,join,admin}=setup(),a=join();assert.equal(admin('bonuspaid',{memberId:a.out.member.id,reference:'test transfer'}).ok,false);for(const task of ['dinner','filmer','host','travel','calendar']){let r=call(a.token,'submit',{taskId:task,revision:0,draft:draft(task)});assert(r.ok,r.error);assert.equal(call(a.token,'review',{memberId:a.out.member.id,taskId:task,revision:1,decision:'approved'}).ok,false);r=admin('review',{memberId:a.out.member.id,taskId:task,revision:1,decision:'approved'});assert(r.ok,r.error);}assert.equal(admin('bonuspaid',{memberId:a.out.member.id,reference:''}).ok,false);assert.equal(admin('bonuspaid',{memberId:a.out.member.id,reference:'test transfer'}).ok,true);assert.equal(admin('bonuspaid',{memberId:a.out.member.id,reference:'retry'}).audit.filter(a=>a.action==='paid').length,1);assert.equal(admin('review',{memberId:a.out.member.id,taskId:'host',revision:2,decision:'changes_requested',feedback:'Cannot change paid basis'}).ok,false);assert.equal(call(a.token,'save',{taskId:'host',revision:2,draft:draft('host','Change approved')}).ok,false);});
test('calendar validation and file access are scoped to the participant',()=>{const{h,call,join}=setup(),a=join(),b=join();h.ctx.ctWrite('files',h.ctx.CT_FILES,{id:'private-file',memberId:a.out.member.id,name:'calendar.pdf',size:100,driveId:'do-not-expose',hash:'hash'});assert.equal(call(b.token,'file',{fileId:'private-file'}).ok,false);const bad=draft('calendar');bad.calendar.events[0].date='2026-02-31';assert.equal(call(a.token,'submit',{taskId:'calendar',draft:bad}).ok,false);bad.calendar.file={id:'private-file'};assert.equal(call(b.token,'save',{taskId:'calendar',draft:bad}).ok,false);assert.equal(call(a.token,'save',{taskId:'calendar',draft:bad}).ok,true);assert(!JSON.stringify(call(a.token,'get')).includes('do-not-expose'));assert.equal(call(a.token,'upload',{file:{name:'exploit.html',data:'test'}}).ok,false);});
test('referrals have separate approved amounts and idempotent payment records',()=>{const{call,join,admin}=setup(),a=join();assert(call(a.token,'submit',{taskId:'referral',draft:draft('referral')}).ok);assert.equal(admin('review',{memberId:a.out.member.id,taskId:'referral',revision:1,decision:'approved',rewardAmount:500}).ok,false);assert(admin('review',{memberId:a.out.member.id,taskId:'referral',revision:1,decision:'approved',rewardAmount:100}).ok);let paid=admin('referralpaid',{memberId:a.out.member.id,taskId:'referral',revision:2,reference:'transfer test'});assert(paid.ok);assert.equal(paid.tasks[0].rewardAmount,100);assert(admin('referralpaid',{memberId:a.out.member.id,taskId:'referral',revision:2,reference:'transfer test'}).ok);assert.equal(admin('list').audit.filter(a=>a.action==='paid').length,1);});
test('steps can be submitted independently, reviewed, reopened, and roll up into task approval',()=>{const{call,join,admin}=setup(),a=join(),id=a.out.member.id;const send=(step,revision,notes)=>call(a.token,'submitstep',{taskId:'host',step,revision,draft:{notes,files:[]}});let out=send(0,0,'Popular creator https://example.com/creator');assert(out.ok,out.error);assert.equal(out.steps[0].status,'submitted');assert.equal(out.tasks[0].status,'draft');assert.equal(out.steps.length,1);assert.equal(call(a.token,'reviewstep',{memberId:id,taskId:'host',step:0,revision:1,decision:'approved'}).code,'FORBIDDEN');assert.equal(admin('reviewstep',{memberId:id,taskId:'host',step:0,revision:0,decision:'approved'}).ok,false);out=admin('reviewstep',{memberId:id,taskId:'host',step:0,revision:1,decision:'approved'});assert(out.ok,out.error);assert.equal(out.tasks[0].status,'draft');assert.equal(send(0,2,'Changed approved evidence').ok,false);assert(send(1,0,'Host confirmed mic and rewards').ok);out=admin('reviewstep',{memberId:id,taskId:'host',step:1,revision:1,decision:'approved'});assert.equal(out.tasks[0].status,'approved');out=admin('reviewstep',{memberId:id,taskId:'host',step:0,revision:2,decision:'changes_requested',feedback:'Add a second video'});assert.equal(out.tasks[0].status,'draft');assert.equal(out.steps[0].status,'changes_requested');assert(send(0,3,'Two creator video links').ok);assert.equal(admin('review',{memberId:id,taskId:'host',revision:out.tasks[0].revision,decision:'approved'}).ok,false);});
test('step evidence stays private and calendar submissions require dates or a file',()=>{const{h,call,join}=setup(),a=join(),b=join();h.ctx.ctWrite('files',h.ctx.CT_FILES,{id:'evidence',memberId:a.out.member.id,name:'menu.pdf',size:100,driveId:'secret-drive',hash:'hash'});const input={taskId:'dinner',step:2,draft:{notes:'',files:[{id:'evidence'}]}};assert.equal(call(b.token,'submitstep',input).ok,false);const result=call(a.token,'submitstep',input);assert(result.ok,result.error);assert(!JSON.stringify(result).includes('secret-drive'));assert.equal(call(b.token,'get').steps.length,0);assert.equal(call(a.token,'submitstep',{taskId:'calendar',step:0,draft:{notes:'Will add later',calendar:{events:[],file:null}}}).ok,false);assert(call(a.token,'submitstep',{taskId:'calendar',step:0,draft:{notes:'Social dates',calendar:{events:[{title:'Mixer',date:'2026-10-31',time:'20:00'}],file:null}}}).ok);assert.equal(call(a.token,'submitstep',{taskId:'host',step:9,draft:{notes:'bad'}}).ok,false);});
test('editing a submitted step invalidates its review snapshot and rejects stale writers',()=>{const{call,join,admin}=setup(),a=join();const payload={taskId:'filmer',step:0,draft:{notes:'First candidate',files:[]}};assert(call(a.token,'submitstep',payload).ok);let out=call(a.token,'savestep',{...payload,revision:1,draft:{notes:'New candidate',files:[]}});assert.equal(out.steps[0].status,'draft');assert.equal(out.steps[0].snapshot.notes,'First candidate');assert.equal(admin('reviewstep',{memberId:a.out.member.id,taskId:'filmer',step:0,revision:2,decision:'approved'}).ok,false);assert.equal(call(a.token,'savestep',{...payload,revision:1}).code,'CONFLICT');});
test('all approved steps across five tasks unlock the bonus and payment locks later step changes',()=>{const{call,join,admin}=setup(),a=join();for(const [taskId,count] of Object.entries({dinner:5,filmer:2,host:2,travel:2,calendar:1})){for(let step=0;step<count;step++){const d={notes:'Evidence for this step',files:[],...(taskId==='calendar'?{calendar:{events:[{title:'Mixer',date:'2026-11-01',time:''}],file:null}}:{})};let r=call(a.token,'submitstep',{taskId,step,draft:d});assert(r.ok,r.error);r=admin('reviewstep',{memberId:a.out.member.id,taskId,step,revision:1,decision:'approved'});assert(r.ok,r.error);}}assert(admin('bonuspaid',{memberId:a.out.member.id,reference:'QA paid record'}).ok);assert.equal(admin('reviewstep',{memberId:a.out.member.id,taskId:'dinner',step:0,revision:2,decision:'changes_requested',feedback:'Reopen paid work'}).ok,false);});

test('deleting a signup is admin-only, idempotent, and hides only that member and their work',()=>{
 const {h,call,join,admin}=setup(),a=join(),b=join(),id=a.out.member.id;
 assert(call(a.token,'submitstep',{taskId:'host',step:0,draft:{notes:'Evidence',files:[]}}).ok);
 assert(call(b.token,'submit',{taskId:'host',draft:draft('host')}).ok);
 for(const who of ['Bijan','Jesse','Luchi'])assert.equal(admin('deleteSignup',{memberId:id},who).code,'FORBIDDEN');
 assert.equal(call(a.token,'deleteSignup',{memberId:id}).code,'FORBIDDEN');
 assert.equal(h.ctx.campusTasksApi({action:'deleteSignup',memberId:id,_key:h.ctx.CONFIG.INVOICE_KEY,who:'Milo'}).code,'FORBIDDEN');
 assert.equal(admin('deleteSignup',{}).ok,false);
 assert.equal(admin('deleteSignup',{memberId:'missing'}).ok,false);
 let out=admin('deleteSignup',{memberId:id},'Arya');assert(out.ok,out.error);
 assert.deepEqual(out.members.map(m=>m.id),[b.out.member.id]);
 assert(out.tasks.every(t=>t.memberId===b.out.member.id));assert.equal(out.steps.length,0);assert(out.audit.every(r=>r.memberId!==id));
 assert.equal(admin('deleteSignup',{memberId:id}).ok,true);
 const deleted=h.ctx.ctRows('deleted',h.ctx.CT_DELETED);assert.equal(deleted.length,1);assert.equal(deleted[0].actor,'Arya');
 assert.equal(h.ctx.ctRows('members',h.ctx.CT_MEMBERS).length,2);assert.equal(h.ctx.ctSteps(id).length,1);
 assert.equal(call(b.token,'get').ok,true);
});
test('deleted signups lose sessions, password login, legacy migration, files, and stale admin actions',()=>{
 const {h,call,join,admin}=setup(),a=join(),id=a.out.member.id;
 assert(call(a.token,'submitstep',{taskId:'host',step:0,draft:{notes:'Evidence',files:[]}}).ok);
 const credential=h.ctx.ctRows('credentials',h.ctx.CT_CREDENTIALS)[0];
 h.ctx.ctWrite('files',h.ctx.CT_FILES,{id:'deleted-file',memberId:id,driveId:'private-drive'});
 const legacy=token(),member=h.ctx.ctMembers()[0];member.tokenHash=h.ctx.ctHash(legacy);h.ctx.ctWrite('members',h.ctx.CT_MEMBERS,member);
 assert(admin('deleteSignup',{memberId:id}).ok);
 for(const [action,payload] of [['get',{}],['save',{taskId:'host',draft:draft('host')}],['savestep',{taskId:'host',step:0,draft:{notes:'Stale'}}],['upload',{file:{}}],['file',{fileId:'deleted-file'}]])assert.equal(call(a.token,action,payload).code,'AUTH_REQUIRED',action);
 assert.equal(call('','login',{email:credential.email,proof:'b'.repeat(64)}).code,'INVALID_LOGIN');
 assert.equal(call(legacy,'signup',{email:'legacy@example.com',name:'Legacy',schoolId:'duke',salt:'a'.repeat(32),proof:'b'.repeat(64)}).code,'LEGACY_NOT_FOUND');
 assert.equal(admin('adminfile',{fileId:'deleted-file'}).ok,false);
 assert.equal(admin('reviewstep',{memberId:id,taskId:'host',step:0,revision:1,decision:'approved'}).ok,false);
 assert.equal(admin('bonuspaid',{memberId:id,reference:'stale'}).ok,false);
 const fresh=call('','signup',{email:credential.email,name:'Fresh',schoolId:'duke',salt:'c'.repeat(32),proof:'d'.repeat(64)});assert(fresh.ok,fresh.error);assert.notEqual(fresh.member.id,id);assert.equal(fresh.tasks.length,0);assert.equal(fresh.steps.length,0);
 assert.equal(call('','login',{email:credential.email,proof:'b'.repeat(64)}).ok,false);
 assert.equal(call('','login',{email:credential.email,proof:'d'.repeat(64)}).ok,true);
 assert.equal(call(a.token,'get').ok,false);
});
test('deletion preserves paid rewards and their audit records in storage',()=>{
 const {h,call,join,admin}=setup(),a=join(),id=a.out.member.id;
 assert(call(a.token,'submit',{taskId:'referral',draft:draft('referral')}).ok);
 assert(admin('review',{memberId:id,taskId:'referral',revision:1,decision:'approved',rewardAmount:100}).ok);
 assert(admin('referralpaid',{memberId:id,taskId:'referral',revision:2,reference:'existing payment'}).ok);
 assert(admin('deleteSignup',{memberId:id}).ok);
 assert.equal(h.ctx.ctTasks(id)[0].paymentReference,'existing payment');
 assert.equal(h.ctx.ctRows('audit',h.ctx.CT_AUDIT).filter(r=>r.memberId===id&&r.action==='paid').length,1);
});
