import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const context={};vm.runInNewContext(fs.readFileSync(new URL('../invoice/chapters.js',import.meta.url),'utf8'),context);const {unitsFrom,SCHOOLS,STATE_NAME}=context.Chapters;
const row=(overrides={})=>({name:'Sigma Chi',school:'Indiana University',active:100,joined:80,registered:'2026-10-01',type:'Fraternity',...overrides});
test('campus aliases and casing group repetitions without adding member counts',()=>{const us=unitsFrom([row(),row({name:' sigma chi ',school:'Indiana University - Bloomington',active:110,joined:0})]);assert.equal(us.length,1);assert.equal(us[0].joined,80);assert.equal(us[0].size,100);assert.equal(us[0].goal,80);assert.equal(us[0].atGoal,true);assert.equal(us[0].dupes,2);assert.equal(us[0].disputed,true);});
test('distinct organizations and campuses remain separate',()=>{assert.equal(unitsFrom([row(),row({name:'Phi Psi'}),row({school:'Princeton University'})]).length,3);});
test('unknown schools remain visible without a fabricated state or pin',()=>{const u=unitsFrom([row({school:'Unknown College'})])[0];assert.equal(u.placed,false);assert.equal(u.state,'');assert.equal(u.joined,80);});
test('new live schools have verified locations and complete state labels',()=>{for(const school of ['College of Charleston','University of California, Berkeley','Washington & Lee University','Texas State University','George Washington University','University of California, Santa Cruz','High Point University','University of Kansas','Princeton University','University of Rhode Island']){assert(SCHOOLS[school],school);assert(STATE_NAME[SCHOOLS[school][2]],school);}assert.equal(STATE_NAME.ON,'Ontario, Canada');assert.equal(STATE_NAME.WI,'Wisconsin');assert.equal(STATE_NAME.DC,'District of Columbia');});
test('joined and roster always come from one winning registration, ties prefer fuller roster',()=>{const u=unitsFrom([row({active:40,joined:30}),row({active:60,joined:30}),row({active:120,joined:0})])[0];assert.equal(u.size,60);assert.equal(u.joined,30);assert.equal(u.goal,48);assert.equal(u.atGoal,false);});
test('joined counts above the source roster are flagged without altering them',()=>{const u=unitsFrom([row({active:40,joined:166})])[0];assert.equal(u.review,true);assert.equal(u.joined,166);assert.equal(u.size,40);});
