import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {girlsHarness,sample} from './helpers/girls-sheet.mjs';
import {badges,cleanBranches,matches,STEPS} from '../fomo/girls/quiz.mjs';

test('writes every qualification and contact field to a dedicated main-sheet tab',()=>{
 const h=girlsHarness(),b=sample(),r=h.post(b);assert.deepEqual(r,{ok:true,id:b.id});assert.deepEqual(Object.keys(h.sheets),['girls']);const [headers,row]=h.sheets.girls.rows;const saved=Object.fromEntries(headers.map((k,i)=>[k,row[i]]));assert.equal(saved.email,'test@example.com');assert.equal(saved.school,'University of Miami');assert.equal(saved['fraternity connections'],'leader');assert.equal(saved['dinner interest'],'friend');assert.equal(saved.segments,badges(b.answers).join(', '));assert.equal(saved.consent,'yes');assert.equal(saved.status,'new');assert.equal(h.writes,1);
});
test('retrying the same submission ID writes exactly one row',()=>{const h=girlsHarness(),b=sample();assert.equal(h.post(b).ok,true);assert.equal(h.post(b).ok,true);assert.equal(h.writes,1);});
test('public namespace cannot read or update the signup list',()=>{const h=girlsHarness();for(const action of ['list','read','delete','update'])assert.equal(h.post({...sample(),action}).ok,false);assert.equal(h.writes,0);});
test('rejects missing consent, contact information, and student school before creating a sheet',()=>{for(const a of [{consent:false},{consent:'yes'},{name:''},{city:''},{email:'wrong'},{school:''}]){const h=girlsHarness();assert.equal(h.post(sample(a)).ok,false);assert.equal(Object.keys(h.sheets).length,0);}});
test('rejects unknown enum values and malformed answers',()=>{for(const a of [{interests:[]},{interests:['people','people']},{interests:['bad']},{connections:'admin'},{dinners:null},{platform:'Bad platform'},{name:['Person']},{name:'A'.repeat(101)},{grad_year:'twenty'}]){const h=girlsHarness();assert.equal(h.post(sample(a)).ok,false);assert.equal(h.writes,0);}});
test('a non-college visitor can skip all optional filters and still join',()=>{const h=girlsHarness(),b=sample({college:'other',sorority:'skip',creator:'skip',connections:'skip',dinners:'skip'});assert.equal(h.post(b).ok,true);const [headers,row]=h.sheets.girls.rows;for(const k of ['school','graduation year','sorority chapter','platform','audience','fraternity chapter','dinner style'])assert.equal(row[headers.indexOf(k)],'');assert.equal(row[headers.indexOf('segments')],'Social explorer');});
test('escapes spreadsheet formulas without discarding the submitted text',()=>{const h=girlsHarness();assert.equal(h.post(sample({name:'=IMPORTXML("https://example.com")',city:'+123',chapter:'-1',instagram:'@person'})).ok,true);const [headers,row]=h.sheets.girls.rows;for(const k of ['name','city','sorority chapter','instagram'])assert.equal(row[headers.indexOf(k)].startsWith("'"),true);});
test('ignores untrusted segment, status, and source claims',()=>{const h=girlsHarness(),b=sample({segments:'VIP',status:'approved'});b.source='untrusted';h.post(b);const [headers,row]=h.sheets.girls.rows;assert.equal(row[headers.indexOf('status')],'new');assert.equal(row[headers.indexOf('source')],'/girls');assert.equal(row[headers.indexOf('segments')],badges(b.answers).join(', '));});
test('honeypot creates no sheet and invalid identifiers are rejected',()=>{const h=girlsHarness();assert.equal(h.post({...sample(),_hp:'spam'}).ok,true);assert.equal(h.post({...sample(),id:'bad'}).ok,false);assert.equal(Object.keys(h.sheets).length,0);});
test('branch changes remove stale details and personalized badges',()=>{const a=cleanBranches(sample({college:'other',sorority:'none',creator:'none',connections:'none',dinners:'no'}).answers);for(const k of ['school','grad_year','chapter','platform','audience','connection_chapter','dinner_style'])assert.equal(a[k],undefined);assert.deepEqual(badges(a),['Social explorer']);assert.equal(matches(a).length,1);});
test('each front-end answer is accepted by the server and badges agree',()=>{for(const step of STEPS.filter(s=>s.choices&&!s.multi)){for(const [value] of step.choices){const h=girlsHarness(),b=sample({[step.key]:value});assert.equal(h.post(b).ok,true,`${step.key}: ${value}`);const [headers,row]=h.sheets.girls.rows;assert.equal(row[headers.indexOf('segments')],badges(b.answers).join(', '));}}});
test('Girls and existing campus forms target the same deployment',()=>{const form=readFileSync(new URL('../fomo/assets/form.js',import.meta.url),'utf8');const config=readFileSync(new URL('../fomo/girls/config.js',import.meta.url),'utf8');assert.equal(form.match(/^const ENDPOINT = '([^']+)'/m)[1],config.match(/const ENDPOINT = '([^']+)'/)[1]);});

const {MISSIONS,FRAT_REWARD,missionPayload,missionFor,potentialReward}=await import('../fomo/girls/missions.mjs');
function missionSample(ids=['frat'],over={}){const b=sample({referral_school:'University of Miami',dinner_role:'content',internship_role:'culture',...over});return {...b,flow:'missions-v2',missions:ids,answers:missionPayload(b.answers,ids)};}
function savedRow(h){const [headers,row]=h.sheets.girls.rows;return Object.fromEntries(headers.map((k,i)=>[k,row[i]]));}
test('all five missions save with an explicit mission receipt and no earned cash',()=>{const h=girlsHarness(),b=missionSample(MISSIONS.map(m=>m.id));assert.deepEqual(h.post(b),{ok:true,id:b.id,flow:'missions-v2'});const row=savedRow(h);assert.equal(row['fraternity reward'],FRAT_REWARD);assert.equal(row['verified earned amount'],0);assert.equal(row['reward status'],'onboarding pending');assert.equal(row['dinner reward status'],'attendance and content pending');assert.equal(row['internship role'],'culture');assert.deepEqual(JSON.parse(row['mission states']),MISSIONS.map(m=>({mission:m.id,status:'planned'})));});
test('rejects missing or invented missions and incomplete referral targets',()=>{for(const b of [missionSample([]),missionSample(['fake']),missionSample(['frat','frat']),missionSample(['frat'],{referral_school:''}),missionSample(['frat'],{connection_chapter:''})]){const h=girlsHarness();assert.equal(h.post(b).ok,false);assert.equal(h.writes,0);}});
test('referral target is preserved for someone planning a cold introduction',()=>{const h=girlsHarness(),b=missionSample(['frat'],{connections:'none'});assert.equal(h.post(b).ok,true);assert.equal(savedRow(h)['fraternity chapter'],'Sigma Chi at Miami');assert.equal(savedRow(h)['referral university'],'University of Miami');});
test('attending dinner without content never claims a dinner comp',()=>{const h=girlsHarness(),b=missionSample(['dinner'],{dinner_role:'attend'});assert.equal(h.post(b).ok,true);assert.equal(savedRow(h)['dinner reward status'],'not applicable');assert.match(missionFor('dinner',b.answers).reward,/no content comp/);assert.equal(savedRow(h)['fraternity reward'],0);});
test('dinner content requires dinner interest and internship requires a real role',()=>{for(const b of [missionSample(['dinner'],{dinners:'no'}),missionSample(['dinner'],{dinner_role:'fake'}),missionSample(['internship'],{internship_role:'owner'})])assert.equal(girlsHarness().post(b).ok,false);});
test('removing missions clears qualification data and conditional rewards',()=>{const a=missionPayload(missionSample(MISSIONS.map(m=>m.id)).answers,['internship']);assert.equal(a.connections,'skip');assert.equal(a.creator,'skip');assert.equal(a.sorority,'skip');assert.equal(a.dinners,'skip');assert.equal(a.referral_school,undefined);assert.equal(potentialReward(['internship']),0);assert.equal(potentialReward(['frat']),100);});
test('client cannot self-award money, completed missions, or comped dinners',()=>{const h=girlsHarness(),b=missionSample(['frat']);b.earned=100;b.reward=999;b.status='paid';b.answers.reward_status='paid';b.answers.dinner_role='content';b.answers.internship_role='president';assert.equal(h.post(b).ok,true);const row=savedRow(h);assert.equal(row['fraternity reward'],100);assert.equal(row['verified earned amount'],0);assert.equal(row['reward status'],'onboarding pending');assert.equal(row['dinner reward status'],'not applicable');assert.equal(row['dinner role'],'');assert.equal(row['internship role'],'');});
test('adds mission columns to an existing v1 sheet without changing earlier rows',()=>{const h=girlsHarness();h.post(sample());const sheet=h.sheets.girls;sheet.rows[0]=sheet.rows[0].slice(0,24);sheet.rows[1]=sheet.rows[1].slice(0,24);const prior=[...sheet.rows[1]];const b=missionSample();b.id='22345678-1234-4234-8234-123456789012';assert.equal(h.post(b).ok,true);assert.deepEqual([...sheet.rows[1]],prior);assert.equal(sheet.rows.length,3);assert.equal(sheet.rows[0].length,h.context.GIRLS_COLS.length);});
test('retrying a mission signup returns its versioned receipt and one record',()=>{const h=girlsHarness(),b=missionSample();assert.deepEqual(h.post(b),h.post(b));assert.equal(h.writes,1);});
test('stories save separately from videos and preserve shared creator details',()=>{for(const ids of [['stories'],['creator'],['stories','creator']]){const h=girlsHarness(),b=missionSample(ids);assert.equal(h.post(b).ok,true);const row=savedRow(h);assert.equal(row.missions,ids.join(', '));assert.equal(row.creator,b.answers.creator);assert.equal(row.platform,b.answers.platform);assert.equal(row['verified earned amount'],0);}const answers=missionSample(['stories','creator']).answers;assert.equal(missionPayload(answers,['stories']).creator,answers.creator);assert.equal(missionPayload(answers,['creator']).creator,answers.creator);assert.equal(missionPayload(answers,['dinner']).creator,'skip');});
