import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createTaskSchoolsHandler,schoolsFromChapters} from '../server/task-schools.mjs';
import {PROFILE_KEY,loadProfiles,profileMatch,normalizeName,readableAccent,legacyProgress,savedChecks} from '../tasks/profile.js';
import {calendarReady,fileError,validEvent} from '../tasks/calendar.js';
function response(){return{statusCode:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(v){this.statusCode=v;return this;},json(v){this.body=v;return this;},end(){return this;}};}
test('school list includes registered schools with no joins, deduplicates and strips private fields',()=>{const schools=schoolsFromChapters([{school:'San Diego State University',joined:0,contact:'private',password:'private'},{school:'San Diego State University',joined:10},{school:'Duke University',joined:0}]);assert.equal(schools.length,2);assert(schools.every(s=>s.logo));assert(!JSON.stringify(schools).includes('private'));assert(!schools.some(s=>'joined'in s));});
test('school endpoint caches reads, rejects writes and fails closed without source data',async()=>{let calls=0;const handler=createTaskSchoolsHandler({load:async()=>{calls++;return[{school:'Duke University'}];}});const a=response(),b=response();await Promise.all([handler({method:'GET'},a),handler({method:'GET'},b)]);assert.equal(calls,1);assert.equal(a.statusCode,200);assert.equal(a.body.schools[0].name,'Duke University');const c=response();await handler({method:'POST'},c);assert.equal(c.statusCode,405);const d=response();await createTaskSchoolsHandler({load:async()=>{throw Error('private admin credential');}})({method:'GET'},d);assert.equal(d.statusCode,503);assert(!JSON.stringify(d.body).includes('credential'));});
test('profiles restore active identity and keep progress separate by person and school',()=>{const profiles=[{id:'one',name:'Alex Smith',school:{id:'duke',name:'Duke'},progress:{dinner:{checks:[true]}}},{id:'two',name:'Alex Smith',school:{id:'sdsu',name:'SDSU'},progress:{}}];const stored=JSON.stringify({version:2,activeId:'one',profiles});const data=loadProfiles({getItem:k=>k===PROFILE_KEY?stored:null});assert.equal(data.activeId,'one');assert.equal(profileMatch(data.profiles,' alex  smith ','duke').id,'one');assert.equal(profileMatch(data.profiles,'Alex Smith','sdsu').id,'two');assert.equal(profileMatch(data.profiles,'Other Person','duke'),undefined);assert.equal(normalizeName('   '),'');assert.deepEqual(loadProfiles({getItem:()=>'{bad'}).profiles,[]);assert.deepEqual(legacyProgress({getItem:()=>'{"dinner":{"checks":[true]}}'}),{dinner:{checks:[true]}});});
test('calendar completion requires a saved file or valid complete dated events',()=>{assert(!calendarReady({events:[]}));assert(!calendarReady({events:[{title:'Party',date:''}]}));assert(!validEvent({title:'Party',date:'2026-02-31'}));assert(calendarReady({events:[{title:'Party',date:'2026-10-31'}]}));assert(calendarReady({file:{name:'social.pdf'}}));assert(fileError({name:'bad.html',size:10}));assert(fileError({name:'big.pdf',size:11*1024*1024}));assert(fileError({name:'empty.pdf',size:0}));assert.equal(fileError({name:'calendar.xlsx',size:1000}),'');});
test('all five offers and the review-based $100 bonus are present',()=>{const offers=JSON.parse(fs.readFileSync(new URL('../tasks/offers.json',import.meta.url)));assert.equal(offers.length,5);assert.equal(offers[4].id,'calendar');const html=fs.readFileSync(new URL('../tasks/index.html',import.meta.url),'utf8');assert.match(html,/Complete all five tasks/);assert.match(html,/approved by fomo to earn an extra \$100/);assert.match(html,/id="calendar-file"/);assert.equal((html.match(/data-task="/g)||[]).length,5);assert.notEqual(readableAccent('#FFCB05'),'#FFCB05');assert.equal(readableAccent('#00274C'),'#00274c');});

test('dinner accepts either Story or TikTok and preserves previous deliverable checks',()=>{assert.deepEqual(savedChecks('dinner',[true,true,true,true,false,true]),[true,true,true,true,true]);assert.deepEqual(savedChecks('dinner',[true,true,true,true,true,false]),[true,true,true,true,true]);const dinner=JSON.parse(fs.readFileSync(new URL('../tasks/offers.json',import.meta.url)))[0];assert.equal(dinner.tasks.length,5);assert.match(dinner.perk.pitch,/Story of the menu or a/);assert.match(dinner.tasks[4].title,/Stories or TikToks/);});

test('school autocomplete handles abbreviations, nicknames and ambiguous schools within the allowed list',async()=>{const{searchSchools}=await import('../tasks/school-search.js');const schools=['San Diego State University','University of Southern California','University of South Carolina','University of California, Santa Barbara','University of Mississippi','Ohio State University - Columbus','University of Michigan - Ann Arbor'].map(name=>({id:name,name}));assert.equal(searchSchools(schools,'s.d.s.u.')[0].name,'San Diego State University');assert.equal(searchSchools(schools,'USC').length,2);assert.equal(searchSchools(schools,'ucsb')[0].name,'University of California, Santa Barbara');assert.equal(searchSchools(schools,'ole miss')[0].name,'University of Mississippi');assert.equal(searchSchools(schools,'UMich')[0].name,'University of Michigan - Ann Arbor');assert.equal(searchSchools(schools,'san diego')[0].name,'San Diego State University');assert.equal(searchSchools(schools,'not registered').length,0);assert.equal(searchSchools(schools,'NYU').length,0);});
