import test from 'node:test';
import assert from 'node:assert/strict';
import {validate,summarize,arrivals,startFeed} from '../model.mjs';
const chapter=(id,joined=3)=>({id,name:'Sigma Chi',letters:'ΣΧ',school:'School '+id,type:'Fraternity',registered:'2026-10-01',active:10,joined});
const snapshot=(chapters,extra={})=>({live:true,updatedAt:'2026-10-05T12:00:00Z',chapters,...extra});
test('summary preserves actual records and over-roster counts',()=>{const x=summarize([chapter('a',15),chapter('b',0)]);assert.deepEqual(x,{joined:15,active:20,chapters:2,schools:2,ready:1,participation:.75});});
test('validation drops nonpublic fields and rejects malformed counts and duplicate IDs',()=>{const x=validate(snapshot([{...chapter('a'),email:'private',phone:'private'}]));assert.equal(x.chapters[0].email,undefined);for(const bad of [-1,1.2,NaN,'4'])assert.throws(()=>validate(snapshot([chapter('a',bad)])));assert.throws(()=>validate(snapshot([chapter('a'),chapter('a')])));});
test('initial snapshot and unchanged counts never create fake arrivals',()=>{assert.deepEqual(arrivals(null,[chapter('a',5)]),[]);assert.deepEqual(arrivals([chapter('a',5)],[chapter('a',5)]),[]);});
test('arrivals reflect only positive deltas, including newly observed chapters',()=>{const x=arrivals([chapter('a',5),chapter('b',8)],[chapter('a',7),chapter('b',2),chapter('c',4)]);assert.deepEqual(x.map(e=>[e.chapter.id,e.count]),[['a',2],['c',4]]);});
function harness(responses){let i=0;const updates=[],statuses=[],timers=new Map();let key=0;const doc={hidden:false,addEventListener(){},removeEventListener(){}};const feed=startFeed({documentRef:doc,now:()=>Date.parse('2026-10-05T12:00:10Z'),schedule:(f,ms)=>{timers.set(++key,{f,ms});return key;},cancel:k=>timers.delete(k),fetchImpl:async()=>{const value=responses[i++];if(value instanceof Error)throw value;return {ok:true,json:async()=>value};},onData:(s,e)=>updates.push({s,e}),onStatus:s=>statuses.push(s)});return {feed,updates,statuses,timers};}
const tick=()=>new Promise(r=>setImmediate(r));
test('polling emits one genuine arrival, ignores old snapshots and retains data on failure',async()=>{const h=harness([snapshot([chapter('a',5)]),snapshot([chapter('a',7)],{updatedAt:'2026-10-05T12:00:05Z'}),snapshot([chapter('a',3)],{updatedAt:'2026-10-05T11:59:00Z'}),new Error('offline')]);await tick();assert.equal(h.updates[0].e.length,0);await h.feed.refresh();assert.equal(h.updates[1].e[0].count,2);await h.feed.refresh();assert.equal(h.updates.length,2);await h.feed.refresh();assert.equal(h.updates.length,2);assert.equal(h.statuses.at(-1).live,false);h.feed.stop();assert.equal(h.timers.size,0);});
test('stale initial data does not announce all existing members on reconnect',async()=>{const h=harness([snapshot([chapter('a',5)],{stale:true}),snapshot([chapter('a',7)])]);await tick();assert.equal(h.updates[0].e.length,0);await h.feed.refresh();assert.equal(h.updates[1].e.length,0);h.feed.stop();});

import {chapterState,growthSeries,marketRows} from '../model.mjs';
test('target state respects the true 80 percent boundary',()=>{assert.equal(chapterState(chapter('a',8)),'ready');assert.equal(chapterState(chapter('a',7)),'near');assert.equal(chapterState(chapter('a',4)),'building');});
test('cumulative chart includes chapters before visible window, daily additions do not',()=>{const items=[{...chapter('a'),registered:'2026-09-01'},{...chapter('b'),registered:'2026-10-05'}];const rows=growthSeries(items,'2026-10-05T12:00:00Z',7);assert.equal(rows.length,7);assert.equal(rows[0].cumulative,1);assert.equal(rows[0].daily,0);assert.equal(rows.at(-1).cumulative,2);assert.equal(rows.at(-1).daily,1);});
test('market filter combines query, sector and exact target status',()=>{const rows=[chapter('a',8),chapter('b',5),{...chapter('c',9),type:'Sorority'}];assert.deepEqual(marketRows(rows,{type:'Fraternity',signal:'ready'}).map(c=>c.id),['a']);assert.deepEqual(marketRows(rows,{query:'school b',signal:'near'}).map(c=>c.id),['b']);});
test('session change sorts actual deltas and includes newly observed chapters',()=>{const baseline=new Map([['a',5],['b',8]]);const rows=marketRows([chapter('a',7),chapter('b',8),chapter('c',4)],{baseline,signal:'changes',sort:'delta'});assert.deepEqual(rows.map(c=>c.id),['c','a']);});
test('goal celebration fires on an observed crossing, including a multi-member jump',()=>{assert.equal(arrivals([chapter('a',7)],[chapter('a',8)])[0].goalReached,true);assert.equal(arrivals([chapter('a',5)],[chapter('a',10)])[0].goalReached,true);assert.equal(arrivals([chapter('a',8)],[chapter('a',9)])[0].goalReached,false);});
test('initial loads, new above-goal records and roster-only corrections do not claim an observed goal crossing',()=>{assert.deepEqual(arrivals(null,[chapter('a',8)]),[]);assert.equal(arrivals([chapter('b',1)],[chapter('a',9)])[0].goalReached,false);assert.deepEqual(arrivals([chapter('a',5)],[{...chapter('a',5),active:5}]),[]);});
test('goal crossing uses the rounded-up target and duplicate polls stay silent',async()=>{assert.equal(arrivals([{...chapter('a',7),active:11}],[{...chapter('a',8),active:11}])[0].goalReached,false);const h=harness([snapshot([chapter('a',7)]),snapshot([chapter('a',8)]),snapshot([chapter('a',8)])]);await tick();await h.feed.refresh();await h.feed.refresh();assert.equal(h.updates[1].e[0].goalReached,true);assert.deepEqual(h.updates[2].e,[]);h.feed.stop();});
