import * as THREE from 'three';
import { GLTFLoader } from './vendor/GLTFLoader.js';
import { DRACOLoader } from './vendor/DRACOLoader.js';
import { OrbitControls } from './vendor/OrbitControls.js';
const $=id=>document.getElementById(id),stage=$('viewport');
const scene=new THREE.Scene();scene.background=new THREE.Color('#e9ece9');
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true});}catch(e){$('loading').textContent='Your browser could not start 3D graphics. Please open this page in a browser with WebGL enabled.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.localClippingEnabled=true;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.94;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;$('canvas-wrap').appendChild(renderer.domElement);
const camera=new THREE.OrthographicCamera(-8,8,8,-8,.1,150),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.1;controls.minZoom=.55;controls.maxZoom=6;controls.maxPolarAngle=Math.PI/2-.06;controls.minPolarAngle=.001;controls.target.set(0,.55,0);
scene.add(new THREE.HemisphereLight(0xf7f9ff,0xb7a48b,.85));
const light=new THREE.DirectionalLight(0xfff3df,2.2);light.position.set(-3,9,6);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-8,right:8,top:8,bottom:-8,near:.1,far:30});light.shadow.normalBias=.018;light.shadow.bias=-.00008;light.shadow.radius=3;scene.add(light);
const fill=new THREE.DirectionalLight(0xddeaff,.7);fill.position.set(3,7,-6);scene.add(fill);
// A neutral studio environment gives polished metal and glass readable reflections.
const envScene=new THREE.Scene();envScene.background=new THREE.Color(0xbfc9cf);
for(const [position,scale,intensity] of [[[-4,5,3],[3,7,4],3],[[3,6,-4],[5,3,3],2],[[0,8,0],[8,.1,8],2.8]]){const panel=new THREE.Mesh(new THREE.BoxGeometry(...scale),new THREE.MeshBasicMaterial({color:new THREE.Color().setScalar(intensity)}));panel.position.set(...position);envScene.add(panel);}
const pmrem=new THREE.PMREMGenerator(renderer);const environment=pmrem.fromScene(envScene,.12);scene.environment=environment.texture;pmrem.dispose();envScene.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});

const draco=new DRACOLoader().setDecoderPath('./vendor/draco/').setDecoderConfig({type:'wasm'}).setWorkerLimit(2);const loader=new GLTFLoader().setDRACOLoader(draco);
let dirty=true,angle=-Math.PI/4,view='dollhouse',activeModel='previous',loadRevision=0;const cache=new Map(),oldCut=new THREE.Plane(new THREE.Vector3(0,-1,0),1.15);
function home(top=false){view=top?'top':'dollhouse';controls.target.set(0,.55,0);camera.position.set(Math.sin(angle)*(top?.015:12),top?18:12.55,Math.cos(angle)*(top?.015:12));camera.zoom=1;camera.lookAt(controls.target);camera.updateProjectionMatrix();controls.update();['home','side-home'].forEach(id=>$(id).classList.toggle('active',!top));['top','side-top'].forEach(id=>$(id).classList.toggle('active',top));dirty=true;}
function resize(){const w=stage.clientWidth,h=stage.clientHeight,aspect=w/h;const span=Math.max(13.3,12.8/aspect);camera.top=span/2;camera.bottom=-span/2;camera.left=-span*aspect/2;camera.right=span*aspect/2;camera.updateProjectionMatrix();renderer.setSize(w,h);dirty=true;}new ResizeObserver(resize).observe(stage);home();
$('home').onclick=$('side-home').onclick=()=>home();$('top').onclick=$('side-top').onclick=()=>home(true);$('rotate').onclick=()=>{angle+=Math.PI/2;home(view==='top')};$('zoom-in').onclick=()=>zoom(1.2);$('zoom-out').onclick=()=>zoom(1/1.2);function zoom(f){camera.zoom=THREE.MathUtils.clamp(camera.zoom*f,.55,6);camera.updateProjectionMatrix();dirty=true;}
function facingWall(name){if(!$('walls').checked)return false;const dx=camera.position.x-controls.target.x,dz=camera.position.z-controls.target.z;return (name.startsWith('WestWall')&&dx<-.1)||(name.startsWith('EastWall')&&dx>.1)||(name.startsWith('SouthWall')&&dz>.1)||(name.startsWith('NorthWall')&&dz<-.1);}
function visibility(){for(const [type,model] of cache){model.scene.visible=type===activeModel;for(const entry of model.materials){entry.mesh.visible=entry.lower?$('lower').checked:!facingWall(entry.role);}}dirty=true;}
function display(){for(const [type,model] of cache)for(const {mesh,textured,clay} of model.materials){mesh.material=$('texture').checked?textured:clay;mesh.material.clippingPlanes=[];mesh.material.needsUpdate=true;}$('lower').disabled=false;visibility();}
$('walls').onchange=$('texture').onchange=$('lower').onchange=display;
function setModelLabels(type,info){$('new').classList.toggle('active',type==='new');$('previous').classList.toggle('active',type==='previous');$('new').setAttribute('aria-pressed',type==='new');$('previous').setAttribute('aria-pressed',type==='previous');$('model-description').textContent='Scan scale ×1.00';document.querySelector('.model-status').textContent=type==='new'?'MODELED ROOM · SCAN SCALE':'REAL OFFICE SCAN · ORIGINAL SCALE';$('download').href=type==='new'?'assets/room-finished.glb':'assets/room-realistic.glb';$('download').download=type==='new'?'room-finished.glb':'room-scan-reference.glb';if(info)$('model-size').textContent=`${(info.final_triangles/1000).toFixed(0)}k triangles · ${info.glb_mb.toFixed(1)} MB`;}
async function switchModel(type){const revision=++loadRevision;activeModel=type;clearSelection();setModelLabels(type,cache.get(type)?.info);if(cache.has(type)){display();$('loading').hidden=true;return}const loading=$('loading');loading.hidden=false;loading.textContent=type==='new'?'Opening the modeled room…':'Opening the office scan…';try{const [g,info]=await Promise.all([loader.loadAsync(type==='new'?'./assets/room-finished.glb':'./assets/room-realistic.glb'),fetch(type==='new'?'./assets/finished-info.json':'./assets/realistic-info.json').then(r=>r.json())]);const materials=[];g.scene.traverse(o=>{if(!o.isMesh)return;const old=o.material,textured=type==='new'?old.clone():new THREE.MeshBasicMaterial({map:old.map||old.emissiveMap,color:0xffffff,side:THREE.DoubleSide,toneMapped:false});
if(type==='new'){textured.envMapIntensity=.45;o.castShadow=true;o.receiveShadow=true;}
for(const key of ['map','normalMap','roughnessMap'])if(textured[key])textured[key].anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());
if(textured.name==='Glass'&&type==='new'){textured.transparent=false;textured.opacity=1;textured.transmission=.88;textured.thickness=.012;textured.ior=1.45;o.castShadow=false;}
const clay=new THREE.MeshStandardMaterial({color:'#cdd4c8',roughness:.85,side:THREE.DoubleSide});
let owner=o;while(owner.parent&& !owner.name.includes('__'))owner=owner.parent;
if(type!=='new')old.dispose();materials.push({mesh:o,textured,clay,role:owner.name,lower:owner.name.startsWith('LowerLevel')});});scene.add(g.scene);cache.set(type,{scene:g.scene,materials,info});display();if(revision===loadRevision){setModelLabels(type,info);loading.hidden=true;}}catch(e){console.error(e);if(revision!==loadRevision)return;loading.replaceChildren();const text=document.createElement('span');text.textContent='The room could not load. ';const retry=document.createElement('button');retry.textContent='Try again';retry.onclick=()=>switchModel(type);loading.append(text,retry);}}
$('new').onclick=()=>switchModel('new');$('previous').onclick=()=>switchModel('previous');
controls.addEventListener('change',visibility);renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();$('loading').hidden=false;$('loading').textContent='3D view paused. Reload the page to restore it.'});
function frame(){requestAnimationFrame(frame);controls.update();if(!dirty)return;dirty=false;renderer.render(scene,camera);}frame();

const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let pointerStart=null,selected=[];
function clearSelection(){for(const [m,color] of selected)m.emissive.copy(color);selected=[];const label=$('selection');if(label)label.hidden=true;dirty=true;}
renderer.domElement.addEventListener('pointerdown',e=>{pointerStart=[e.clientX,e.clientY];});
renderer.domElement.addEventListener('pointerup',e=>{if(!pointerStart||Math.hypot(e.clientX-pointerStart[0],e.clientY-pointerStart[1])>5)return;clearSelection();if(activeModel!=='new')return;const bounds=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-bounds.left)/bounds.width*2-1,-(e.clientY-bounds.top)/bounds.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(cache.get('new')?.scene.children||[],true).find(h=>{let o=h.object;while(o){if(!o.visible)return false;o=o.parent;}return true;});if(!hit)return;let owner=hit.object;while(owner.parent&&!owner.userData.asset_name)owner=owner.parent;const name=owner.userData.asset_name;if(!name)return;owner.traverse(o=>{if(o.isMesh&&o.material.emissive){selected.push([o.material,o.material.emissive.clone()]);o.material.emissive.set(0x182514);}});$('selection').textContent=name;$('selection').hidden=false;dirty=true;});

switchModel('previous');
