import {STEPS} from './quiz.mjs?v=2';
import {MISSIONS,FRAT_REWARD,potentialReward,missionPayload,introText,missionFor} from './missions.mjs?v=2';
import {ENDPOINT} from './config.js';
const app=document.querySelector('#app');
const KEY='fomo-girls-missions-v2';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fresh=()=>({view:'board',answers:{},missions:[],id:crypto.randomUUID(),submitted:false});
let state=fresh(),editing=null,sending=false,toast='';
try{
 const saved=JSON.parse(sessionStorage.getItem(KEY));
 if(saved&&saved.answers&&Array.isArray(saved.missions)&&saved.missions.every(id=>MISSIONS.some(m=>m.id===id))&&typeof saved.id==='string')state={...saved,view:saved.submitted?'saved':'board'};
 else{const old=JSON.parse(sessionStorage.getItem('fomo-girls-v1'));if(old?.answers)state.answers=old.answers;}
}catch{}
function persist(){try{sessionStorage.setItem(KEY,JSON.stringify(state));}catch{}}
function focusTitle(){const h=app.querySelector('h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}window.scrollTo({top:0,behavior:'instant'});}
function reset(){if(sending)return;state=fresh();toast='';try{sessionStorage.removeItem('fomo-girls-v1');}catch{}persist();render();focusTitle();}
function navigate(view){if(sending)return;state.view=state.submitted?'saved':view;render();focusTitle();}
function input(key,label,placeholder='',required=false,type='text'){
 return `<label class="field">${label}<input name="${key}" type="${type}" value="${esc(state.answers[key])}" placeholder="${esc(placeholder)}" maxlength="${key==='email'?160:100}" ${required?'required':''} ${key==='email'?'autocomplete="email"':key==='name'?'autocomplete="name"':key==='city'?'autocomplete="address-level2"':''}></label>`;
}
function select(key,label,options,required=false){
 return `<label class="field">${label}<select name="${key}" ${required?'required':''}><option value="">${required?'Choose your role':'Optional — choose your fit'}</option>${options.map(([v,l])=>`<option value="${v}" ${state.answers[key]===v?'selected':''}>${l}</option>`).join('')}</select></label>`;
}
function qualifier(key,label){return select(key,label,STEPS.find(q=>q.key===key).choices.map(([v,l])=>[v,l]),true);}
function capture(form){for(const el of form.elements){if(!el.name||el.name==='website')continue;state.answers[el.name]=el.type==='checkbox'?el.checked:el.value.trim();}persist();}
function missionButton(m,label){return `<button class="primary" data-mission="${m.id}">${label||'Explore mission'} <span>↗</span></button>`;}
function journal(){return `<aside class="mission-journal"><div class="journal-top"><span>YOUR PLAYBOOK</span><span>${state.missions.length} / ${MISSIONS.length} pinned</span></div><div class="slot-track" aria-label="${state.missions.length} missions pinned">${MISSIONS.map(m=>`<span class="${state.missions.includes(m.id)?'filled':''}">${state.missions.includes(m.id)?m.icon:'＋'}</span>`).join('')}</div><h3>${state.missions.length?'You’ve got a plan.':'Make your first move.'}</h3><p>${state.missions.length?'Explore more cards or save your playbook to get the team involved.':'Open a mission. Find your angle. Pin the ones you want to take on.'}</p>${state.missions.length?`<ul class="pinned-list">${state.missions.map(id=>{const m=MISSIONS.find(x=>x.id===id);return `<li><span>${m.icon} ${m.short}</span><button data-remove="${id}" aria-label="Remove ${m.title}">×</button></li>`;}).join('')}</ul>`:''}<div class="reward-total"><span>Fraternity reward to work toward</span><b>$${potentialReward(state.missions)}</b></div><p class="micro">${state.missions.includes('frat')?'Earned after verified fraternity onboarding. Pinning a mission earns no cash.':'The fraternity mission pays $100 after verified onboarding.'}</p><button class="primary" id="save-plan" ${!state.missions.length?'disabled':''}>Save my playbook <span>↗</span></button><button class="start-over" id="reset">Start over ↺</button></aside>`;}
function board(){const frat=MISSIONS[0],pinned=state.missions.includes('frat');return `<section class="mission-board"><div class="board-intro"><div><p class="eyebrow">The girls who make it happen</p><h1>make moves.<br><em>get rewarded.</em></h1><p>Your connections. Your creativity. Your next opportunity.<br>Pick a mission and turn what you bring into something real.</p></div><div class="board-stamp"><span>fomo girls</span><b>YOUR<br>MOVE.</b><span>✳ OPEN THE POSSIBILITIES</span></div></div><div class="board-layout"><div class="mission-deck"><article class="bounty-card ${pinned?'is-pinned':''}"><div class="bounty-top"><span class="mission-label">↗ FEATURED CASH MISSION</span><span class="status-tag">${pinned?'✓ PINNED TO YOUR PLAYBOOK':'OPEN TO EXPLORE'}</span></div><div class="bounty-body"><div><h2>you know the guys.<br>make the intro.</h2><p>Bring a fraternity onto FOMO.<br>When they complete onboarding, you earn:</p></div><div class="bounty-amount"><strong>$${FRAT_REWARD}</strong><span>PER VERIFIED FRATERNITY REFERRAL</span></div></div><div class="bounty-bottom">${missionButton(frat,pinned?'Edit my mission':'Show me the mission')}<span>Introduction → onboarding → $100</span></div><p class="bounty-fine">FOMO confirms your referral and completed chapter onboarding before the reward is earned.</p></article><div class="deck-heading"><h2>More ways to play.</h2><span>Explore in any order. Pick your mix.</span></div><div class="side-missions">${MISSIONS.slice(1).map(m=>`<button class="mission-card ${state.missions.includes(m.id)?'is-pinned':''}" data-mission="${m.id}"><span class="mission-card-top"><span class="mission-icon">${m.icon}</span><span>${state.missions.includes(m.id)?'✓ PINNED':m.tag}</span></span><h3>${m.title}</h3><p>${m.description}</p><span class="mission-benefit">${m.reward}</span><span class="mission-link">${state.missions.includes(m.id)?'Edit mission':'Explore mission'} ↗</span></button>`).join('')}</div></div>${journal()}</div>${state.missions.length?`<div class="mobile-playbook"><span>${state.missions.length} missions pinned</span><button class="primary" id="mobile-save">Save playbook <span>↗</span></button></div>`:''}<div class="board-toast" role="status">${esc(toast)}</div><div class="how-to-play"><span>01 <b>Pick your mission.</b></span><span>02 <b>Make a real contribution.</b></span><span>03 <b>Unlock its reward.</b></span></div></section>`;}
function missionFields(id){switch(id){
 case 'frat':return qualifier('connections','Your route into the chapter')+input('connection_chapter','Choose a fraternity','e.g. Sigma Chi',true)+input('referral_school','Their university','e.g. University of Miami',true);
 case 'creator':return qualifier('creator','Your creator mode')+select('platform','Your main platform',[['Instagram','Instagram'],['TikTok','TikTok'],['YouTube','YouTube'],['Other','Other']])+select('audience','Your audience',['Just starting','Under 1k','1k–5k','5k–10k','10k–50k','50k+'].map(v=>[v,v]));
 case 'circle':return qualifier('sorority','Your sorority connection')+input('chapter','Your sorority / school (optional)','e.g. Alpha Phi at USC');
 case 'internship':return select('internship_role','Where you want to lead',[['president','Campus president — lead the team'],['growth','Growth — bring people in'],['partnerships','Partnerships — build relationships'],['content','Content — shape the story'],['culture','Culture — make the plans']],true);
 case 'dinner':return qualifier('dinners','Your dinner interest')+select('dinner_role','How you’d like to show up',[['content','Attend + make content for a comped dinner'],['attend','Just attend — no content comp'],['bring','Bring my girls — no content comp'],['host','Help organize or host']],true)+select('dinner_style','Your kind of table',['A small, cozy group','Creators & collaborators','Girls’ night','Surprise me'].map(v=>[v,v]));
}}
function openMission(id){if(sending||state.submitted)return;editing=id;const m=MISSIONS.find(x=>x.id===id),dialog=document.querySelector('#mission-dialog');dialog.innerHTML=`<button class="close" type="button" aria-label="Close mission">×</button><p class="eyebrow">${m.tag}</p><h2 id="mission-title">${m.title}</h2><div class="mission-prize ${id==='frat'?'cash':''}"><b>${m.reward}</b><p>${m.benefit}</p></div><ol class="mission-steps">${m.steps.map(s=>`<li>${s}</li>`).join('')}</ol><form id="mission-form"><p class="eyebrow">Set your next move</p><div class="fields">${missionFields(id)}</div><p class="micro">${id==='frat'?'Name the chapter, not your friends. Saving this plan does not claim a completed referral.':'A pinned mission is an expression of interest. The team will confirm the next step.'}</p><button class="primary" type="submit">${state.missions.includes(id)?'Update my mission':m.action} <span>＋</span></button></form>`;
 dialog.querySelector('.close').onclick=()=>dialog.close();
 dialog.querySelector('form').onsubmit=e=>{e.preventDefault();capture(e.target);if(id==='dinner'&&state.answers.dinner_role==='content'&&!['yes','friend','maybe'].includes(state.answers.dinners)){e.target.querySelector('[name=dinners]').setCustomValidity('Choose a dinner interest to take on the content mission.');e.target.reportValidity();return;}if(!state.missions.includes(id))state.missions.push(id);toast=`${m.short} mission pinned. Your playbook is taking shape.`;persist();dialog.close();render();app.querySelector(`[data-mission="${id}"]`)?.focus({preventScroll:true});};
 dialog.querySelector('[name=dinners]')?.addEventListener('change',e=>e.target.setCustomValidity(''));
 dialog.showModal();
}
function checkout(){return `<section class="playbook-checkout"><button class="back" id="back-board">← Back to my missions</button><div class="checkout-layout"><div><p class="eyebrow">Make it yours</p><h1>save your<br><em>next moves.</em></h1><p>One profile for your whole playbook. The team will use this to help you take the next step.</p><div class="checkout-missions">${state.missions.map(id=>{const m=missionFor(id,state.answers);return `<div><span>${m.icon} ${m.short}</span><b>${m.reward}</b></div>`;}).join('')}</div><p class="micro">Your $100 fraternity reward is earned after FOMO verifies the referral and completed onboarding. Other opportunities are confirmed individually.</p></div><form id="profile-form"><p class="eyebrow">Your home base</p>${qualifier('college','Pick your world')}<div class="fields" id="school-fields">${schoolFields()}</div><div class="fields"><div class="field-row">${input('name','Your name','First and last name',true)}${input('city','Your city','e.g. Miami, FL',true)}</div>${input('email','Email','you@example.com',true,'email')}${input('instagram','Instagram (optional)','@yourname')}<label class="consent"><input type="checkbox" name="consent" required ${state.answers.consent?'checked':''}><span>I agree that FOMO can save my profile and missions and contact me about next steps. Pinning missions doesn’t mean a reward has been earned.</span></label><label class="honeypot" aria-hidden="true">Website<input name="website" tabindex="-1" autocomplete="off"></label></div><p class="error" id="error" role="alert"></p><button class="primary" type="submit" id="submit">Save my playbook <span>↗</span></button></form></div></section>`;}
function schoolFields(){return ['student','graduate'].includes(state.answers.college)?input('school',state.answers.college==='student'?'Your university':'Your university (optional)','e.g. University of Miami',state.answers.college==='student'):'';}
function saved(){const a=missionPayload(state.answers,state.missions);return `<section class="saved-playbook"><p class="eyebrow">PLAYBOOK SAVED · NEXT MOVE IS YOURS</p><h1>let’s make moves,<br><em>${esc(a.name.split(' ')[0])}.</em></h1><p>Your missions are registered. FOMO will follow up at ${esc(a.email)}.</p><div class="saved-summary"><span><b>${state.missions.length}</b> missions pinned</span><span><b>$${potentialReward(state.missions)}</b> fraternity reward available</span><span><b>$0</b> earned so far</span></div><div class="saved-missions">${state.missions.map(id=>{const m=missionFor(id,a);return `<article class="saved-mission"><div class="saved-mission-head"><span class="mission-icon">${m.icon}</span><span class="status-tag">PLAN REGISTERED</span></div><h2>${m.title}</h2><p>${id==='frat'?`${esc(a.connection_chapter)} · ${esc(a.referral_school)}`:m.benefit}</p><ol class="mission-steps">${m.steps.map((s,i)=>`<li class="${i===0?'registered':''}">${s}${i===0?' ✓':''}</li>`).join('')}</ol>${id==='frat'?`<div class="next-move"><p class="eyebrow">Your next move: open the conversation</p><p class="intro-copy">${esc(introText(a))}</p><button class="primary" id="copy-intro">Copy my intro <span>↗</span></button><p class="micro">This copies a message for you to send. It doesn’t send anything or mark an introduction complete. FOMO will follow up to coordinate onboarding and verify attribution.</p></div>`:'<p class="micro">Next: wait for the team to confirm a relevant opportunity and its details.</p>'}</article>`;}).join('')}</div><p class="micro">This page confirms your saved plan. It does not display live onboarding or payout progress.</p><div class="result-actions"><button class="primary" id="share">Bring a friend <span>↗</span></button><button class="text-button" id="download">Save my playbook ↓</button></div><p id="share-status" class="micro" role="status"></p><button class="start-over" id="reset">Clear this device & start over ↺</button></section>`;}
function render(){
 app.innerHTML=state.submitted?saved():state.view==='checkout'?checkout():board();
 document.querySelector('#nav-start').textContent=state.submitted?'My playbook ↗':'My missions ↗';
 app.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>openMission(b.dataset.mission));
 app.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.missions=state.missions.filter(id=>id!==b.dataset.remove);state.answers=missionPayload(state.answers,state.missions);toast='Mission removed. Explore another whenever you’re ready.';persist();render();});
 app.querySelector('#reset')?.addEventListener('click',reset);
 app.querySelector('#save-plan')?.addEventListener('click',()=>navigate('checkout'));
 app.querySelector('#mobile-save')?.addEventListener('click',()=>navigate('checkout'));
 app.querySelector('#back-board')?.addEventListener('click',()=>navigate('board'));
 const form=app.querySelector('#profile-form');
 if(form){form.addEventListener('input',()=>capture(form));form.querySelector('[name=college]').onchange=()=>{capture(form);form.querySelector('#school-fields').innerHTML=schoolFields();};form.onsubmit=e=>{e.preventDefault();capture(form);submit();};}
 app.querySelector('#copy-intro')?.addEventListener('click',()=>copy(introText(state.answers),'Intro copied. Send it when you’re ready.'));
 app.querySelector('#share')?.addEventListener('click',()=>copy(new URL('/girls',location.origin).href,'Portal link copied. Bring your girls.'));
 app.querySelector('#download')?.addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({missions:state.missions,answers:missionPayload(state.answers,state.missions),conditionalReward:potentialReward(state.missions),earned:0},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='my-fomo-playbook.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
}
async function copy(text,confirmation){const status=app.querySelector('#share-status');try{await navigator.clipboard.writeText(text);status.textContent=confirmation;}catch{status.textContent='Couldn’t copy automatically. Select and copy the text above, or share this page’s address.';}}
async function submit(){
 if(sending)return;sending=true;const form=app.querySelector('#profile-form'),error=app.querySelector('#error'),button=app.querySelector('#submit');const controls=[...app.querySelectorAll('button,input,select')];controls.forEach(el=>el.disabled=true);error.textContent='';button.textContent='Saving your playbook…';
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),25000);
 try{
  const response=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({_api:'girls',action:'join',flow:'missions-v2',id:state.id,missions:state.missions,answers:missionPayload(state.answers,state.missions),_hp:form.querySelector('[name=website]').value}),signal:controller.signal});
  if(!response.ok)throw new Error('We couldn’t save your playbook. Your missions are still here. Please retry.');
  const data=await response.json();
  if(!data.ok||data.id!==state.id||data.flow!=='missions-v2')throw new Error(data.error&&data.error!=='unknown form'?data.error:'Mission signup isn’t connected yet. Your playbook is saved in this tab. Please try again later.');
  state.submitted=true;state.view='saved';persist();render();focusTitle();
 }catch(err){error.textContent=err.name==='AbortError'?'Saving took too long. Retry safely; the same playbook won’t be saved twice.':err.message;}
 finally{clearTimeout(timeout);sending=false;controls.forEach(el=>el.disabled=false);if(button.isConnected)button.innerHTML='Save my playbook <span>↗</span>';}
}
const missionDialog=document.createElement('dialog');missionDialog.id='mission-dialog';missionDialog.setAttribute('aria-labelledby','mission-title');document.body.append(missionDialog);
missionDialog.addEventListener('close',()=>{editing=null;});
document.querySelector('#nav-start').onclick=()=>navigate('board');
document.querySelector('#privacy-button').onclick=()=>document.querySelector('#privacy').showModal();
document.querySelector('#privacy .close').onclick=()=>document.querySelector('#privacy').close();
render();
