"""Generate the metric dictionary and universe/coverage audit from the release."""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
read=lambda p:json.loads((ROOT/p).read_text())
data=read('data/campuses.json');metrics=read('config/metrics.json');weights=read('config/profiles.json')['default'];candidates=read('data/candidates.json')
def cell(x):return str(x).replace('|','/').replace('\n',' ')
def save(name,lines):(ROOT/'docs'/name).write_text('\n'.join(lines)+'\n')
lines=['# Metric dictionary', '', 'Generated from the committed configuration and observations. All anchors and weights are editable policy choices. Zero-weight fields remain descriptive until enabled. Missing observations are null, excluded from observed means, and retained in completeness and unresolved-score bounds.', '', 'For every metric below, `outputs/observations.csv` records the raw value, normalization, effective default weight, confidence, period, qualifier, URL, publisher and access date for every campus. Quality uses the rubric in METHODOLOGY.md. A stated prospective source is a collection plan, not a claim that data were collected.', '']
rationales={
'enrollment':'Non-distance students receive the most weight because campaigns need a physically addressable audience; total size provides scale, while verified residents would measure a concentrated audience.',
'demographics':'The default brief is a broad 18–24 audience. Other demographic fields are descriptive; clients must explicitly enable their own target and weight.',
'greek':'Participation share receives 60% of category weight; chapter breadth 30%; absolute member scale 10%. These are related measures of the same ecosystem, not additive student populations.',
'creators':'An audited creator rate would carry 70%; documented content infrastructure carries 30%. Program presence alone cannot substantiate creator density.',
'programs':'Relevant degree share carries 70%; award volume 20%; audited organizations 10%. Academic awards are a repeatable talent-pipeline proxy, not ambassador availability.',
'customers':'A same-scope active-customer rate is the only enabled footprint metric. No client data were supplied.',
'cost':'Lodging 40%, labor and venue 20% each, permitting and travel 10% each. Lodging is only an administrative benchmark; remaining costs are uncollected.',
'geography':'Nearest scheduled-service airport distance carries 60%; metro membership and cluster potential 20% each. This is preliminary accessibility, not a travel itinerary.',
'performance':'CAC 35%, conversion 25%, contribution ROI 25%, engagement 15%. Output volumes remain descriptive to avoid rewarding spend alone.'}
prospective={'on_campus_residents':'University housing occupancy report','verified_creators_per_1000':'Audited public creator roster + same-scope undergraduate denominator; CREATORS.md','creator_program_present':'Official student content/ambassador program page','relevant_clubs':'Audited official student-organization directory','labor_hourly_usd':'Dated local staffing vendor quote; an explicitly labeled BLS occupation proxy can be added separately','venue_day_usd':'Dated venue quote or published rental schedule','permit_days':'Published campus permitting policy for the specified event type','travel_quote_usd':'Dated origin/destination, dates, mode and party-size quote'}
for category in weights:
    lines+=['## '+category, '',f'Default category weight: **{weights[category]}**. '+rationales[category],'']
    for key,m in metrics.items():
        if m['category']!=category:continue
        obs=[s['metrics'][key] for s in data['schools'] if s['metrics'][key]['value'] is not None]
        ids=sorted({sid for o in obs for sid in o['source_ids']})
        source='; '.join(f'[{sid}]({data["sources"][sid]["url"]})' for sid in ids)
        if not source:source='Not collected. Prospective: '+prospective.get(key,'Supplied attributable client aggregate export, imported privately')
        n=m['normalization'];rule=f"target={n['target']}, tolerance={n['tolerance']}" if n['method']=='target' else f"{n['method']}{' inverse' if n.get('invert') else ''}, anchors {n['min']} to {n['max']}"
        notes=list(dict.fromkeys(o.get('note','') for o in obs if o.get('note')))
        # University-specific details remain in the complete observation ledger.
        calc=notes[0] if len(notes)==1 else 'Per-campus calculation/scope notes in observations.csv; definition below applies to all.'
        lines += [f'### `{key}` — {m["label"]}', '',m['definition'],'',f'- Unit: {m["unit"]}. Normalization: {rule}.',f'- Within-category weight: {m["weight"]}; effective default weight: {weights[category]*m["weight"]/sum(v["weight"] for v in metrics.values() if v["category"]==category):g} of 100.',f'- Calculation/scope: {calc}',f'- Coverage: {len(obs)}/{len(data["schools"])}. Update: {m["update_frequency"]}.',f'- Sources: {source}','']
save('METRICS.md',lines)
lines=['# Initial universe audit', '', 'Accessed 2026-09-29. Discovery is the union of two independent student-review publishers, followed by an official NCES enrollment filter. Discovery rank is never a score input.', '', '- [Niche 2027 party/social top 50, page 1](https://www.niche.com/colleges/search/top-party-schools/) and [page 2](https://www.niche.com/colleges/search/top-party-schools/?page=2).', '- [The Princeton Review 2027 Lots of Greek Life, 25 schools](https://www.princetonreview.com/college-rankings?rankings=lots-greek-life).', '- [NCES EF2023A enrollment](https://nces.ed.gov/ipeds/datacenter/data/ef2023a.zip), matched by UNITID.', '', 'Initial union: 68 institutions; 53 had at least 5,000 undergraduates; the largest 50 became the release universe. Fifteen were below threshold; three eligible institutions fell below the size cutoff. The table preserves all 68 candidates. Later client-requested additions need not appear on either discovery list and are retained with their reason.', '', 'WSU selection used its published institutional headcount, but this is a multi-campus scope. It is retained as a flagged discovery candidate and excluded from Pullman population/program scoring; the model does not pass that system count off as Pullman enrollment.', '', '| Campus | UNITID | Niche rank | Princeton rank | Fall 2023 undergrads | Selection |','|---|---|---:|---:|---:|---|']
for c in sorted(candidates,key=lambda s:(not s['selected'],-s.get('undergraduates_2023',0),s['unitid'])):
    reason='Selected' if c['selected'] else ('Below 5,000 undergraduates' if c.get('undergraduates_2023',0)<5000 else 'Outside largest 50 eligible')
    if c.get('expansion_reason'):reason+='; '+c['expansion_reason']
    campus=next((s for s in data['schools'] if s['unitid']==c['unitid']),None)
    enrollment=c.get('undergraduates_2023',campus['metrics']['undergraduates']['value'] if campus else '—')
    lines.append('| '+' | '.join(cell(v) for v in [c['school'],c['unitid'],c['niche_party_rank'] or '—',c['princeton_greek_rank'] or '—',enrollment,reason])+' |')
save('UNIVERSE.md',lines)
lines=['# Research log and outstanding data', '', f'Release access date: {data["as_of"]}. {len(data["sources"])} distinct source records. This is a bounded public-data collection, not an assertion that all public information has been exhausted. An unavailable value means no comparable verified observation was collected; it does not mean the campus has none.', '', '## Collection decisions', '', '- Retrieved the pinned official NCES directory, fall-enrollment/age/residency/distance and completions files. Tested 2024 enrollment ZIP variants returned 404, so this release explicitly uses comparable Fall 2023 data; it does not claim that no newer release exists elsewhere. Raw-file hashes and URLs are in data/extracts/manifest.json.', '- Used official FSL reports/pages rather than third-party percentages for scoring. Undated pages remain undated. “Over”, approximate and rounded counts retain qualifiers.', '- Michigan State: dated Fall 2025 report preferred over inconsistent undated chapter counts. Iowa: selected community-page percentage; a differing admissions figure is disclosed in the observation note. Miami Ohio: retained the published Spring 2026 total even though separately published subtotals do not reconcile.', '- Denominators such as “student body” were not silently relabeled as undergraduate. Ole Miss participation is derived only from matching Spring 2024 member and Oxford undergraduate counts. Illinois likewise uses same-report Spring 2026 member and undergraduate counts. No percentage divides different-year membership by NCES enrollment.', '- FY2027 GSA file is already published but becomes effective October 1, 2026. It is a forward-planning benchmark, not a September 2026 quote. Only exact institutional ZIP matches with unambiguous rate schedules are accepted.', '- Airport observations are a snapshot of an open geographic dataset. Scheduled-service flag does not validate a flight route or trip cost.', '- Reviewed content programs, campus-specific university-advertised content roles, and named club subsets supplement the first pass. Advertised opportunities are a weaker proxy, not proof of current staffing or a creator census. Exact coverage is below.', '- Two university sources identify undergraduate residents; bed capacity, projected move-ins and mixed graduate/undergraduate occupancy were not substituted. No first-party customer/campaign data or comparable event quotes, staffing rates or permitting lead times were verified.', '', '## Metric coverage', '', '| Metric | Available | Missing |','|---|---:|---:|']
for k,m in metrics.items():
    count=sum(s['metrics'][k]['value'] is not None for s in data['schools']);lines.append(f'| {m["label"]} | {count} | {len(data["schools"])-count} |')
lines+=['','## Campus-specific Greek/content evidence gaps','','Universal gaps above apply to every campus; the following table exposes the remaining campus-specific qualitative-research gaps. See observations.csv for missing reasons, years, qualifiers and provenance.','','| Campus | Missing Greek measures | Content program | Relevant club audit |','|---|---|---|---|']
for s in sorted(data['schools'],key=lambda s:s['school']):
    greek=', '.join(metrics[k]['label'] for k in ['greek_pct','greek_chapters','greek_members'] if s['metrics'][k]['value'] is None) or 'All three observed'
    lines.append('| '+' | '.join([cell(s['school']),greek,'Observed; not density' if s['metrics']['creator_program_present']['value'] is not None else 'Uncollected','Audited subset only' if s['metrics']['relevant_clubs']['value'] is not None else 'Uncollected'])+' |')
save('RESEARCH_LOG.md',lines)
print('Updated metric dictionary, universe audit and research coverage log.')
